/* Source behavior only. Browser layout and input latency are measured separately. */
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('output/blueprint/index.html','utf8');
const data=JSON.parse(html.match(/<script id="blueprint-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);
const numberedAsset=data.assets.find(a=>a.image_number===19);
numberedAsset.previews=[{url:'media/previews/test-480.webp',size:[480,320]},{url:'media/previews/test-960.webp',size:[960,640]}];
const elements=new Map();
function element(id){if(!elements.has(id))elements.set(id,{value:'',textContent:'',innerHTML:'',dataset:{},addEventListener(){},insertAdjacentHTML(){},classList:{toggle(){}},setAttribute(){},removeAttribute(){}});return elements.get(id);}
element('blueprint-data').textContent=JSON.stringify(data);
let serializations=0;
const env={JSON:{parse:JSON.parse,stringify(...args){serializations++;return JSON.stringify(...args);}},document:{getElementById:element,querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){},scrollTo(){}},location:{hash:'#search'},navigator:{},setTimeout,clearTimeout,clearInterval,setInterval,console};
vm.createContext(env);
for(const file of ['app','experience','inspection','design','review_state','review','inline'])vm.runInContext(fs.readFileSync('tools/html_blueprint_ui/'+file+'.js','utf8'),env);
element('search').value='이미지 19';
const numbered=vm.runInContext('searchResults()',env);
assert.equal((numbered.match(/href="#inspect\//g)||[]).length,1,'Number search must retain its exact single image identity');
element('search').value='not-a-real-match';serializations=0;
vm.runInContext('match(D.assets[0]);match(D.assets[0]);match(D.assets[0])',env);
assert.equal(serializations,1,'Repeated source search must serialize an immutable record only once');
vm.runInContext("var dynamicReview={comment:'before'}",env);
element('search').value='before';assert(vm.runInContext('match(dynamicReview)',env));
vm.runInContext("dynamicReview.comment='after'",env);
assert(!vm.runInContext('match(dynamicReview)',env),'Mutable comments must not use a stale source-search cache');
element('search').value='after';assert(vm.runInContext('match(dynamicReview)',env));
assert.equal(vm.runInContext("[{name:'after one'},{name:'after two'}].filter(match).length",env),2,'Array filter callback indexes must not become search terms');
vm.runInContext('var searchRenders=0;render=()=>searchRenders++',env);
element('search').value='ㅎ';element('search').oninput({isComposing:true});
assert.equal(vm.runInContext('searchRenders',env),0,'IME composition must not repeatedly render partial Korean queries');
element('search').value='한글';element('search').oncompositionend();element('search').oninput({isComposing:false});
assert.equal(vm.runInContext('searchRenders',env),1,'Committed composition must search once, including the following input event');
const attributes={};env.overflowTable={clientWidth:320,scrollWidth:1100,dataset:{},querySelector:s=>s==='thead'?{textContent:'상대 · 약점 · 대응'}:null,closest:()=>null,setAttribute:(k,v)=>attributes[k]=v,removeAttribute:k=>delete attributes[k]};
vm.runInContext('updateScrollableTables([overflowTable])',env);
assert.equal(attributes.tabindex,'0');assert.equal(attributes.role,'region');assert(attributes['aria-label'].includes('상대'));
env.overflowTable.clientWidth=1200;vm.runInContext('updateScrollableTables([overflowTable])',env);
assert(!('tabindex' in attributes),'Fitting tables must not add unnecessary keyboard stops');
env.originalUrl=numberedAsset.url;
const previewMarkup=vm.runInContext('previewImageAttributes(originalUrl)',env);
assert(previewMarkup.includes('src="media/previews/test-480.webp"'));
assert(previewMarkup.includes('test-960.webp 960w'));
assert(previewMarkup.includes('data-original-src="'+numberedAsset.url+'"'));
assert(vm.runInContext("previewImageAttributes('../../not-in-catalog.png')",env).includes('src="../../not-in-catalog.png"'),'Unknown images retain their original URL');
let inlineReview='';const imageAttributes={'src':'media/previews/test-480.webp','data-original-src':numberedAsset.url};
const image={dataset:{},getAttribute:k=>imageAttributes[k],setAttribute:(k,v)=>imageAttributes[k]=v,closest:s=>s==='[data-numbered-image]'?null:{insertAdjacentHTML:(where,value)=>inlineReview+=value}};
env.document.querySelectorAll=s=>s==='#main img'?[image]:[];
vm.runInContext('attachImageReviews()',env);
assert(inlineReview.includes('이미지 19'),'A derived image must retain its source image number');
assert(inlineReview.includes('data-user-review="asset:'+numberedAsset.id+'"'),'A derived image must retain the original user-comment identity');
console.log('Search performance behavior passed: exact numbers, immutable cache, live comments and Korean composition');
