extends SceneTree

const Run := preload("res://src/run/vertical_slice_run_state.gd")
const Starter := preload("res://src/run/vertical_slice_starter_manual_catalog.gd")
var checks := 0
var failures := 0

func _initialize() -> void:
    create_timer(60.0).timeout.connect(func(): printerr("FRAME_PROLOGUE_TIMEOUT"); quit(1))
    var run = Run.new()
    if not expect(run.has_method("start_new_frame_run"), "new game must expose the approved prologue entry point"): return
    expect(run.call("start_new_frame_run", 12345, "first-journey"), "frame run starts")
    expect(run.is_frame_run() and run.get_current_screen() == "PROLOGUE", "first screen is prologue")
    roundtrip(run)
    expect(not run.complete_frame_practice(0), "practice cannot be completed out of order")
    expect(not run.select_first_journey_choice("observe"), "event cannot be claimed before arrival")
    expect(run.advance() and run.get_current_screen() == "SETUP", "prologue leads to manual selection")
    expect(not run.advance(), "unselected manuals cannot skip setup")
    var starter = Starter.new()
    var ids: Array = Starter.STARTER_MANUAL_IDS.slice(0, 4)
    expect(not run.confirm_setup_loadout(ids.slice(0, 3), starter.build_mastery(ids.slice(0, 3))), "three manuals rejected")
    expect(run.confirm_setup_loadout(ids, starter.build_mastery(ids)), "four three-star manuals accepted")
    expect(run.advance() and run.get_current_screen() == "TUTORIAL", "setup leads to rules")
    roundtrip(run)
    for step in range(3):
        expect(run.get_frame_onboarding().tutorial_step == step, "rules step is stable")
        expect(run.advance(), "advance one rule at a time")
        roundtrip(run)
    expect(not run.advance(), "practice gates first journey")
    expect(not run.complete_frame_practice(100), "outside-window placement rejected")
    expect(run.complete_frame_practice(20), "a legal timing placement completes small practice")
    roundtrip(run)
    expect(run.advance() and run.get_current_screen() == "FIRST_JOURNEY", "practice leads to first route map")
    expect(not run.advance(), "first journey cannot be skipped")
    expect(run.get_first_journey_options().is_empty(), "event choices appear only after node entry")
    expect(run.enter_first_journey(), "enter noncombat event node")
    expect(not run.enter_first_journey(), "event node cannot be entered twice")
    roundtrip(run)
    expect(run.get_first_journey_options().size() == 3, "three actual stat/safe choices")
    var before: Dictionary = run.export_snapshot()
    var restored = Run.new()
    expect(restored.import_snapshot(before).ok, "copy before event")
    expect(run.select_first_journey_choice("observe"), "resolve first event")
    expect(restored.select_first_journey_choice("observe"), "restored event resolves")
    expect(run.export_snapshot() == restored.export_snapshot(), "restarting does not reroll event")
    var awarded: Dictionary = run.export_snapshot()
    expect(not run.select_first_journey_choice("assist"), "second choice cannot duplicate reward")
    expect(run.export_snapshot() == awarded, "rejected duplicate leaves state untouched")
    roundtrip(run)
    var forged := awarded.duplicate(true)
    forged.frame.onboarding.journey_receipt.training += 1
    expect(not run.validate_snapshot(forged).ok, "forged event reward rejected")
    forged = awarded.duplicate(true)
    forged.progression.free_training_pool += 1
    expect(not run.validate_snapshot(forged).ok, "double counted progression rejected")
    expect(run.advance() and run.get_current_screen() == "BRIEFING", "event confirmation leads to first briefing")
    expect(run.get_frame_onboarding().completed and run.route_visits == 0, "intro ends once without consuming later route nodes")
    roundtrip(run)
    expect(run.advance() and run.get_current_screen() == "COMBAT", "first fight starts after briefing")
    roundtrip(run)
    var failed_run = Run.new()
    expect(failed_run.import_snapshot(run.export_snapshot()).ok, "loss fixture starts from real frame combat boundary")
    expect(failed_run.mark_combat_finished({"outcome": "loss", "player_resources": failed_run.get_player_run_resources()}) and failed_run.advance(), "loss fixture reaches retry choice")
    expect(failed_run.end_failed_run(), "player can end failed frame run")
    expect(failed_run.validate_snapshot(failed_run.export_snapshot()).ok, "ending frame run clears retired onboarding state consistently")
    expect(run.mark_combat_finished({"outcome": "win", "player_resources": run.get_player_run_resources()}), "frame run accepts recorded first battle result")
    expect(run.advance(), "recorded review leads to result")
    roundtrip(run)
    var result_model = preload("res://src/run/vertical_slice_result_model.gd").new()
    expect(run.set_pending_result_reward(result_model.build_reward_receipt("free_training", "", run.get_player_manual_loadout(), run.get_current_opponent())), "select actual battle reward")
    expect(run.advance(), "reward confirmation continues usual route")
    for step in range(4):
        roundtrip(run)
        var options: Array = run.get_jianghu_options()
        var route_id: String = str(options[0].id)
        expect(run.select_jianghu_node(route_id, step), "later route accepts its offered node")
        if route_id == "event":
            roundtrip(run)
            expect(run.select_jianghu_node("event.leave", step), "later event preserves normal resolution")
        roundtrip(run)
        expect(run.advance(), "later route continues")
    expect(run.get_current_screen() == "BRIEFING" and run.duel_index == 2, "four later nodes reach second duel")
    expect(not run.enter_first_journey() and not run.select_first_journey_choice("leave"), "completed intro never reopens")
    roundtrip(run)
    var skipped := run.export_snapshot()
    skipped.flow_history.erase("TUTORIAL")
    expect(not run.validate_snapshot(skipped).ok, "frame snapshot cannot omit required introduction")
    var legacy = Run.new()
    expect(legacy.start_new_variable_run(45, "legacy"), "legacy entry remains usable")
    expect(not legacy.export_snapshot().has("frame"), "legacy snapshot bytes do not gain frame field")
    expect(restored.import_snapshot(legacy.export_snapshot()).ok and not restored.is_frame_run(), "import legacy clears frame mode")
    if failures == 0: print("FRAME_PROLOGUE_PASS checks=%d" % checks)
    quit(0 if failures == 0 else 1)

func expect(value: bool, message: String) -> bool:
    checks += 1
    if value: return true
    printerr("FRAME_PROLOGUE_FAIL: " + message)
    failures += 1
    quit(1)
    return false

func roundtrip(run) -> void:
    var saved: Dictionary = run.export_snapshot()
    expect(run.validate_snapshot(saved).ok, "current domain snapshot validates: " + run.get_current_screen())
    var copy = Run.new()
    expect(copy.import_snapshot(saved).ok, "snapshot imports")
    expect(copy.export_snapshot() == saved, "snapshot restores without reapplying effects")
    var json_copy = Run.new()
    var json_dto: Dictionary = JSON.parse_string(JSON.stringify(saved))
    expect(json_copy.import_snapshot(json_dto).ok, "JSON numeric transport imports")
    expect(json_copy.export_snapshot() == saved, "JSON roundtrip restores same domain snapshot")
