extends SceneTree
const Run = preload("res://src/run/vertical_slice_run_state.gd")
const Legacy = preload("res://src/run/vertical_slice_opponent_catalog.gd")
func _initialize():
    create_timer(90.0).timeout.connect(func(): printerr("verify_variable_run_state TIMEOUT"); quit(1))
    var run = Run.new()
    assert(run.has_method("start_new_variable_run"), "New runs must freeze the approved variable roster")
    assert(run.call("start_new_variable_run", 12345, "test-run"))
    var dto: Dictionary = run.export_snapshot()
    assert(dto.resolved_encounters.size() == 10)
    assert(run.validate_snapshot(dto).ok)
    var copy = Run.new()
    assert(copy.import_snapshot(dto).ok)
    assert(copy.export_snapshot() == dto)
    assert(copy.get_current_opponent().manuals.size() >= 2)
    var corrupt = dto.duplicate(true)
    corrupt.resolved_encounters[0].manuals[0].mastery = true
    assert(not copy.validate_snapshot(corrupt).ok)
    var legacy = Run.new()
    assert(legacy.configure_opponents(Legacy.new(), 20260820))
    assert(legacy.start_new_run())
    assert(not legacy.export_snapshot().has("ruleset_id"))
    assert(copy.import_snapshot(legacy.export_snapshot()).ok)
    assert(not copy.export_snapshot().has("ruleset_id"))
    print("VARIABLE_RUN_STATE_PASS")
    quit()
