'use strict';
const D=JSON.parse(document.getElementById('blueprint-data').textContent);
const main=document.getElementById('main'), search=document.getElementById('search');
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const src=p=>'../../'+encodeURI(p).replace(/#/g,'%23').replace(/\?/g,'%3F');
const nav=[['maps','화면 연결 · 아틀라스'],['home','전체 보기'],['reader','게임 이해 · 112개 항목'],['people','인물 · 무공'],['assets','자산 · 모션 도감'],['motion','연출 영상'],['pm','작업 · 일정'],['evidence','실행 · 검수 기록'],['resume','다음 작업 이어가기']];
const badge=(s,w=false)=>`<span class="badge ${w?'warn':''}">${E(s)}</span>`;
const scope=a=>a.scope==='PR342_CANDIDATE'?'PR #342 후보':'main 원본';
const approval=a=>a.details?.retired?(a.details.disposal.status==='DELETED_BY_USER_REQUEST'?'삭제 완료':'폐기 처리 · 삭제대기'):a.approval==='USER_APPROVED'?(a.details?.appearance_only?'외형 확정 · 모션 별도':'승인 기록 있음'):'최종 시각 승인 미확인';
const assetById=new Map(D.assets.map(a=>[a.id,a]));
const byId=id=>assetById.get(id);
// Only immutable publication records belong in this cache; editable review data does not.
const sourceSearchRecords=new WeakSet([...(D.assets||[]),...(D.pages||[]),...(D.people||[]),...(D.manuals||[]),...(D.pm?.items||[]),...(D.inspection?.records||[])]),sourceSearchText=new WeakMap();
let searchInputValue=null,searchQuery='';
function normalizedSearch(){if(searchInputValue!==search.value){searchInputValue=search.value;searchQuery=search.value.trim().toLowerCase();}return searchQuery;}
function match(value){const query=normalizedSearch();if(!query)return true;const immutable=value!==null&&typeof value==='object'&&sourceSearchRecords.has(value);let text=immutable?sourceSearchText.get(value):undefined;if(text===undefined){text=JSON.stringify(value).toLowerCase();if(immutable)sourceSearchText.set(value,text);}return text.includes(query);}
const previewSources=new Map(D.assets.filter(a=>a.available).map(a=>[decodeURI(a.url),a]));
function previewImageAttributes(url,sizes='(max-width:680px) 100vw, (max-width:1100px) 50vw, 320px'){
 const asset=previewSources.get(decodeURI(url)),rows=asset?.previews||[];
 return `src="${E(rows[0]?.url||url)}" data-original-src="${E(url)}" decoding="async"${asset?.size?` width="${asset.size[0]}" height="${asset.size[1]}"`:''}${rows.length?` srcset="${rows.map(p=>E(p.url)+' '+p.size[0]+'w').join(', ')}" sizes="${E(sizes)}"`:''}`;
}
const raw=(v,title='원본 상세')=>`<details><summary>${E(title)}</summary><pre>${E(JSON.stringify(v,null,2))}</pre></details>`;
const link=(p,label=p,revision=null)=>`<a href="${revision?'https://github.com/alsdmlals4-eng/Ten-Paces-Hidden-Moves/blob/'+encodeURIComponent(revision)+'/'+encodeURI(p):src(p)}" target="_blank" rel="noopener">${E(label)} ↗</a>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${E(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${E(typeof v==='object'?JSON.stringify(v):v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
let motionTimer=null, assetFilter='all', assetCategory='all';
document.getElementById('nav').innerHTML=nav.map(([id,title],i)=>`<a href="#${id}" data-nav="${id}"><span class="num">0${i+1}</span>${E(title)}</a>`).join('');
document.getElementById('freshness').textContent=`발행 ${new Date(D.generated_at).toLocaleString('ko-KR')}\n기준 ${D.source_revision.slice(0,10)}\nGitHub 관측 ${new Date(D.pm.github.observed_at).toLocaleString('ko-KR')}\n정적 화면 · 이후 변경은 재생성 필요`;
function title(k,t,desc=''){return `<div class="eyebrow">${E(k)}</div><h1>${E(t)}</h1>${desc?`<p class="lead">${E(desc)}</p>`:''}`;}
function tile(a){return `<a class="tile" href="#asset/${encodeURIComponent(a.id)}">${a.available?`<img loading="lazy" ${previewImageAttributes(a.url)} alt="${E(a.name)}">`:'<p class="empty">'+(a.details?.retired?'폐기 처리 완료 · 이력 보기':'파일 없음')+'</p>'}<div class="caption"><h3>${E(a.name)}</h3>${badge(scope(a),a.scope!=='MAIN_SOURCE')}${badge(approval(a),a.approval!=='USER_APPROVED')}<small>${a.consumers.length?'사용처 '+a.consumers.length+'곳':'실제 코드 직접 참조 미확인'}</small></div></a>`;}
function home(){
 const cover=D.pages[0].blocks.find(b=>b.kind==='image');
 return `<section class="hero"><div><div class="eyebrow">TEN PACES, HIDDEN MOVES</div><h1>상대의 수를 읽고,<br>나의 무공으로 답한다.</h1><p class="lead">열 칸의 거리 위에서 펼치는 1대1 무협 전술 게임.<br>기획부터 승인 원화, 실제 구현과 다음 작업까지 한곳에서 확인합니다.</p><a href="#reader">게임의 전체 설명 읽기 →</a></div>${cover?`<button class="media-button" data-image="${E(src(cover.path))}" aria-label="화면 아틀라스 확대"><img src="${E(src(cover.path))}" alt="십보강호 화면 아틀라스 · 시각 목표와 과거 실행 화면"></button>`:''}</section>
 <div class="stats"><div class="stat"><strong>${D.pages.length}</strong><span>기존 블루프린트 설명 단위</span></div><div class="stat"><strong>${D.people.length}</strong><span>승인 인물 · 단계별 무공</span></div><div class="stat"><strong>${D.assets.length}</strong><span>승인·후보 자산과 적용본</span></div><div class="stat"><strong>${D.manuals.length}</strong><span>무공서 · 실제 데이터 연결</span></div></div>
 <h2>읽기 → 결단 → 해결 → 복기</h2><div class="flow">${[['강호행로','회복·수련·단서의 기회비용을 비교한다.'],['전투 준비','공개 거리와 지난 수를 보고 해금 기술을 배치한다.'],['합과 해결','3수 → 해결 → 3수 → 해결 → 4수. 결과를 연출로 읽는다.'],['성장과 재도전','승패의 이유를 복기하고 파훼 선택지를 넓힌다.']].map(([t,b])=>`<div class="step"><strong>${t}</strong>${b}</div>`).join('')}</div>
 <div class="notice">이 화면은 저장소 원본의 파생본입니다. 기획 승인·구현·실행 확인·사람 검수는 서로 다릅니다. PR #342의 게임 개선과 모션은 별도 후보이며 main 완료로 표시하지 않습니다.</div>
 <div class="grid">${[['people','강호의 인물과 무공','인물별 삽화·성장·전술·대응을 비교합니다.'],['assets','원화와 모션 확인','승인 파일과 실제 적용본, 미연결 자산을 확인합니다.'],['pm','지금 할 일','진행 작업·의존성·검증·다음 작업을 확인합니다.'],['resume','다른 대화에서 이어가기','원본 읽기 순서와 보호 범위를 전달합니다.']].map(([id,t,b])=>`<a class="tile card" href="#${id}"><h3>${t}</h3><p>${b}</p></a>`).join('')}</div>
 <details><summary>현재 재개 지점 · 원본 기록</summary><div class="panel"><p>${E(D.active_context)}</p><div class="links">${link('[기획서]/00_프로젝트_허브/ACTIVE_CONTEXT.md','현재 기록 원본')}${link('docs/blueprint/HTML_MIGRATION_SPEC.md','승인한 HTML 설계')}</div></div></details>`;
}
function reader(id){
 if(!id)return title('GAME BLUEPRINT','게임 이해','전체 설명·표·이미지를 여섯 종류로 모았습니다. 과거 본문의 시점 표현은 현재 구현·PM과 구별해 읽습니다.')+`<div class="notice">2026-09-11 승인 기획을 구성하는 공통 원본에서 생성했습니다. 본문의 당시 ‘후보·구현 전’ 표시는 역사 문구입니다. 이후 구현 여부는 작업·검수 화면의 근거를 확인하세요. ${link('output/pdf/TEN_PACES_HUMAN_BLUEPRINT_20260911_APPROVAL_REVIEW.pdf','보존된 승인 PDF 비교')}</div>${D.reader_groups.map(g=>`<section><h2>${E(g.label)}</h2><div class="toc">${g.pages.map(id=>D.pages.find(p=>p.id===id)).filter(match).map(p=>`<a href="#reader/${p.id}">${E(p.title)}</a>`).join('')}</div></section>`).join('')}`;
 const i=D.pages.findIndex(p=>p.id===id),p=D.pages[i];if(!p)return missing();
 return title('GAME BLUEPRINT · '+(i+1)+' / '+D.pages.length,p.title,p.subtitle)+`<div class="notice">승인 기획 본문 · 당시 상태: ${E(p.historical_state)}. 현재 구현 완료를 뜻하지 않습니다. <a href="#pm">현재 작업 확인</a></div><div class="pager">${i?`<a href="#reader/${D.pages[i-1].id}">← 이전</a>`:'<span></span>'}<a href="#reader">전체 목차</a>${i+1<D.pages.length?`<a href="#reader/${D.pages[i+1].id}">다음 →</a>`:''}</div>`+`<details class="approved-page"><summary>승인 당시 페이지 · 도식과 원래 배치 보기</summary><button class="media-button" data-image="${E(p.approved_page.url)}" aria-label="승인 페이지 확대"><img loading="lazy" src="${E(p.approved_page.url)}" alt="${E(p.title)}의 승인 당시 보존 화면"></button><p>기존 승인 PDF의 읽기 전용 렌더이며 현재 게임 실행 화면이 아닙니다.</p></details>`+readerContent(p)+`<div class="links">${link('tools/build_human_blueprint_complete.py','공통 설명 원본')}${link('docs/blueprint/READING_STRUCTURE.md','읽기 구조')}</div>`;
}
function block(b){switch(b.kind){case 'text':return `<p>${E(b.text)}</p>`;case 'note':return `<div class="notice">${E(b.text)}</div>`;case 'panel':return `<section class="panel reader-block"><h3>${E(b.title)}</h3><p>${E(b.text)}</p></section>`;case 'table':return b.group_first_column?groupedEventTable(b.headers,b.rows):table(b.headers,b.rows);case 'flow':return `<div class="flow">${b.items.map(([t,v])=>`<div class="step"><strong>${E(t)}</strong>${E(v)}</div>`).join('')}</div>`;case 'image':return `<figure class="reader-block"><button class="media-button" data-image="${E(src(b.path))}" aria-label="이미지 원본 확대">${b.region?`<svg viewBox="${b.region.join(' ')}" role="img" aria-label="원본의 지정 영역"><image href="${E(src(b.path))}" width="${b.size[0]}" height="${b.size[1]}"/></svg>`:`<img loading="lazy" src="${E(src(b.path))}" alt="기획 설명 자료">`}</button><figcaption><small>${E(b.path)}</small></figcaption></figure>`;case 'link':return `<p><a href="${E(b.url)}" target="_blank" rel="noopener">${E(b.url)}</a></p>`;default:return '';}}
function people(id,unfiltered=false){
 const person=D.people.find(p=>p.id===id);
 if(person){const art=D.assets.find(a=>a.path===person.portrait);return title('CHARACTER',person.name+' · '+person.identity,person.personality)+`<div class="split"><div>${art?tile(art):''}</div><section><h2>읽을 수 있는 습관</h2><p>${E(person.habit)}</p><div class="notice">반례 · ${E(person.counterexample)}</div><h2>조합과 대응</h2>${Object.entries(person.tactics).map(([k,v])=>`<p><strong>${E(({combination:'조합',weakness:'약점',counterplay:'대응'})[k])}</strong><br>${E(v)}</p>`).join('')}<a href="#assets">관련 자산·모션 도감 →</a></section></div><h2>1전부터 10전까지 · 승인 성장표</h2>${table(['비무','별호','능력치','보유 무공·성수'],[...person.stages].reverse().map(s=>[s.stage,s.epithet,s.stats.join(' / '),s.owned_manuals.map(m=>m.name+' '+m.mastery+'성').join('\n')]))}<div class="links">${link('data/run/approved_opponent_stages_v2.json','게임에 연결된 단계 데이터')}${link('src/run/variable_opponent_roster.gd','상대 편성 구현')}<a href="#pm">관련 잔여 작업</a></div>`;}
 return title('CHARACTERS & MARTIAL ARTS','강호의 인물과 무공','같은 인물의 정체성과 무공 조합, 성장에 따라 달라지는 대응을 비교합니다. 역할 분류는 기존 기획을 따릅니다.')+`<div class="gallery">${D.people.filter(p=>unfiltered||match(p)).map(p=>`<a class="tile" href="#people/${E(p.id)}"><img loading="lazy" ${previewImageAttributes(src(p.portrait))} alt="${E(p.name)}"><div class="caption"><h3>${E(p.name)} · ${E(p.identity)}</h3><small>${E(p.role)} · ${E(p.manual)}</small></div></a>`).join('')}</div><h2>무공서 · 실제 데이터</h2>${commonGrowthTable()}${D.manuals.filter(match).map(m=>`<details><summary>${E(m.name??m.manual_name??m.manual_id)}</summary>${manualTables(m)}${raw(m,'기술·절초·조건과 효과 데이터')}${link('data/cards/martial_manuals/'+m.manual_id+'.json','무공 원본')}</details>`).join('')}`;
}
function category(a){const p=a.path;return p.includes('motion/')||a.grid?'motion':p.includes('background')?'background':p.includes('vfx')?'effect':p.includes('ui/')?'ui':'art';}
function assets(){const list=D.assets.filter(a=>match(a)&&(assetFilter==='all'||(assetFilter==='approved'?a.approval==='USER_APPROVED':a.scope==='PR342_CANDIDATE'))&&(assetCategory==='all'||category(a)===assetCategory));return title('ASSET LIBRARY','자산 · 모션 도감','확정 원화와 게임 적용본, 작업 중인 후보를 함께 찾습니다. 승인과 실제 연결 상태는 별도로 표시합니다.')+`<div class="filters"><label>상태 <select id="asset-filter">${[['all','전체'],['approved','승인 기록 있음'],['candidate','PR #342 후보']].map(([v,t])=>`<option value="${v}" ${assetFilter===v?'selected':''}>${t}</option>`).join('')}</select></label><label>종류 <select id="asset-category">${[['all','전체 종류'],['art','인물 · 삽화'],['motion','모션 · 포즈'],['background','배경'],['effect','이펙트'],['ui','UI']].map(([v,t])=>`<option value="${v}" ${assetCategory===v?'selected':''}>${t}</option>`).join('')}</select></label>${badge(list.length+'개 표시')}</div><div class="gallery">${list.map(tile).join('')}</div>${list.length?'':missing('검색에 맞는 자산이 없습니다.')}`;}
function asset(id){const a=byId(id);if(!a)return missing();return title('ASSET DETAIL',a.name)+`<div class="row">${badge(scope(a),a.scope!=='MAIN_SOURCE')}${badge(approval(a),a.approval!=='USER_APPROVED')}<a href="#assets">← 전체 도감</a></div><div class="split"><div>${a.available?`<button class="media-button" data-image="${E(a.url)}" aria-label="자산 원본 확대"><img class="art-large" src="${E(a.url)}" alt="${E(a.name)}"></button>`:missing('원본 파일 없음')}</div><div><h2>승인과 사용처</h2><p>${E(a.approval_record)}</p><div class="notice">${a.consumers.length?'직접 참조 파일이 있습니다. 참조 존재는 실제 화면 검증과 다릅니다.':'실제 코드에 연결된 직접 참조를 확인하지 못했습니다. 외형 승인만으로 모션 적용 완료가 되지 않습니다.'}</div><div class="scene-links">${a.consumers.map(p=>link(p,p,a.revision)).join('')}</div><p><small>파일 ${E(a.path)}<br>SHA-256 ${E(a.sha256)}</small></p>${link(a.owner,'자산·승인 원본',a.details?.appearance_only?null:a.revision)}<p><button data-request="${E(a.id)}">이 자산 수정 요청 복사</button></p>${raw(a.details,'생성·승인·영역 상세 기록')}</div></div>${a.grid?`<h2>모션·포즈 확인</h2><div class="notice">원본의 ${a.grid[0]}×${a.grid[1]} 영역을 확인합니다. ${a.sequence?.length?'실제 코드의 포즈 순서를 열람합니다. 재생 속도는 도감 열람용이며 게임의 접근·합·타격·복귀 재현이 아닙니다.':'포즈별 탐색만 제공하며 확인되지 않은 재생 순서나 타이밍을 만들지 않습니다.'} 원본의 크로마키 색상도 그대로 보입니다.</div><canvas id="motion" class="motion-stage" aria-label="포즈 프레임 미리보기"></canvas><div class="row">${a.sequence?.length?'<button id="motion-play">재생</button><label>열람 배속 <select id="motion-speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label>':''}<button id="motion-prev">이전 포즈</button><button id="motion-next">다음 포즈</button><output id="frame-label"></output></div><input id="motion-frame" type="range" min="0" max="${a.grid[0]*a.grid[1]-1}" value="0" aria-label="포즈 번호">`:''}<h2>원본·적용본 연결</h2><div class="gallery">${(a.related_assets??[]).map(byId).filter(Boolean).map(tile).join('')||'<p>등록된 원본·적용본 연결 없음</p>'}</div><h2>관련 작업·검증</h2><div class="links">${(a.related_work??[]).map(id=>`<a href="#pm/${E(id)}">${E(id)} 작업·인수 조건</a>`).join('')||'<p>사용처가 일치하는 개별 작업 기록 없음 · 아래 전체 PM에서 확인</p>'}</div><a href="#pm">PM에서 미완료·검수 상태 확인 →</a><p><a href="#evidence">실제 Godot 실행 근거 확인 →</a></p>`;}
function pm(focus,unfiltered=false){return title('PROJECT MANAGEMENT','작업 · 일정','기존 작업 기록에서 읽은 상태입니다. 테스트 개수나 이미지 수를 게임 완성률로 환산하지 않습니다.')+`<div class="notice">PR #337은 ${E(D.pm.github.prs['337'].mergedAt)} 병합 완료입니다. 과거 활성 PR 표시를 교정했습니다. PR #342는 별도의 미병합 게임 후보입니다.</div><h2>현재 작업</h2>${raw(D.pm.current,'현재 운영 원본의 상태')}<div class="tasks">${D.pm.items.filter(t=>(unfiltered||match(t))&&(!focus||t.work_item_id===focus)).map(t=>`<article class="card"><div class="task-title"><h3>${E(t.title??t.work_item_id)}</h3>${badge(t.status,true)}</div><p>${E(t.next_action??'다음 작업 기록 없음')}</p><small>계획/예상 일정: ${E(t.planned_date??'미정')} · 의존 작업: ${E((t.depends_on??[]).join(', ')||'없음')}</small><p>${badge(t.scope==='PR342_CANDIDATE'?'PR #342 작업 기록':'현재 작업 기록',t.scope==='PR342_CANDIDATE')}</p>${raw({checklist:t.checklist,verification:t.verification,consumers:t.actual_consumers},'완료 기준·검증·사용처')}<div class="links"><a href="#inspect/${encodeURIComponent('task:'+(t.scope==='PR342_CANDIDATE'?'candidate:':'')+t.work_item_id)}">내 상태·코멘트 →</a>${link(t.source,'작업 원본',t.revision)}${t.canon_owner?link(t.canon_owner,'책임 원본',t.revision):''}</div></article>`).join('')}</div><h2>전체 개발 로드맵</h2><details><summary>기존 로드맵 본문 · 현재 상태와 역사 기록 구분</summary><pre>${E(D.roadmap)}</pre></details><h2>관측한 관련 PR</h2>${table(['PR','상태','제목','관측 당시 커밋'],Object.values(D.pm.github.prs).map(p=>['#'+p.number,p.state+(p.isDraft?' · Draft':''),p.title,p.headRefOid.slice(0,10)]))}`;}
function evidence(){const p=D.candidate?.presets;return title('EVIDENCE & DAILY RECORD','실행 · 검수 기록','자동 검사, 실제 Godot 실행, 사용자 검수와 최종 승인 근거를 분리합니다.')+`<div class="notice">HTML 자산 재생은 게임 실행 증거가 아닙니다. 아래 촬영 자료는 기존 실행 당시의 증거이며 현재 모든 변경의 실행 완료를 뜻하지 않습니다. 사람 재미·Android 실기기·출시 검수는 별도입니다.</div><h2>실제 Godot에서 촬영한 장면</h2><div class="gallery">${['execution-024.png'].map(p=>`<button class="tile" data-image="${E(src('docs/blueprint/evidence/'+p))}"><img loading="lazy" src="${E(src('docs/blueprint/evidence/'+p))}" alt="과거 Godot 실행 ${p}"><div class="caption">${E(p)} · 과거 실행 촬영</div></button>`).join('')}</div><p>${link('docs/blueprint/evidence/capture.json','촬영 당시 입력·결과 원본')}${link('docs/operations/2026-09-11_VARIABLE_ROSTER_IMPLEMENTATION.md','main의 단계별 상대 구현 검증')}</p><h2>직접 실행하는 경로</h2><div class="panel"><p>이 작업 폴더의 project.godot를 Godot에서 열고 실행합니다. 새 여정 → 시작 무공 → 상대 브리핑 → 전투 준비/해결 순서로 확인합니다.</p><p>PR #342 후보 게임은 해당 작업 브랜치에서 실행해야 합니다. HTML 링크가 로컬 실행 파일을 자동 실행하지는 않습니다. Web export는 아직 검증되지 않았습니다.</p><div class="links">${link('project.godot','현재 프로젝트')}${link('scenes/run/vertical_slice_shell.tscn','실제 시작 씬')}</div></div>${p?`<h2>무공 카드별 연출 연결 · PR #342 후보</h2><p>${E(p.pose_gap)}</p>${table(['연출군','시간','이동 비율','준비 비율','타격 멈춤','포즈'],Object.entries(p.families).map(([k,v])=>[k,v.duration,v.travel,v.windup,v.hit_stop,v.pose]))}${raw(p.cards,'카드 → 연출 프리셋 연결')}${link('data/presentation/combat_motion_presets.json','후보 연출 설정 원본',D.candidate.revision)}`:''}<h2>날짜별 누적 작업일지</h2><div class="notice">기존 월간 작업일지에 날짜별로 누적합니다. PR #342에서 이어받은 과거 게임 작업 기록은 후보 이력입니다. 기록 작성일과 실제 작업일·촬영일을 혼동하지 않습니다.</div>${D.journal?journal(D.journal):missing('현재 원본에 작업일지가 없습니다.')}<h2>사용자 확인 질문</h2><p>원하는 인물의 승인 그림과 실제 적용 여부를 찾을 수 있나요? 다음 AI가 이미 끝난 일과 남은 일을 구별할 수 있나요? 이는 자동 테스트로 대신 완료 처리하지 않습니다.</p>`;}
function journal(j){return (j.timeline??[]).map(row=>`<div class="date-row"><h3>${E(row[0])}</h3><p>${E(row[1])}</p></div>`).join('')+raw(j.daily_summaries??[],'날짜별 상세 요약')+link('docs/operations/AI_USAGE_EVIDENCE_2026_09.json','누적 작업일지 원본');}
function resumeText(id=''){return `십보강호 작업을 이어가줘.\n작업 폴더: ${D.workspace}\n브랜치: ${D.branch}\nHTML 발행 당시 기준: ${D.source_revision}\nHTML 생성 시각: ${D.generated_at}\n${id?'확인할 항목: '+id+'\n':''}AI 브라우저 검수: python tools/serve_html_blueprint.py 실행 후 output/blueprint/preview-session.json의 HTTP 주소를 같은 PC에 연결된 브라우저 도구로 열어줘. 클라우드 AI의 localhost는 이 PC가 아니므로 접속 미확인을 완료로 쓰지 마.\n먼저 최신 AGENTS.md → docs/BASE_RULES_VERSION.md → 통합 작업 계약 → [기획서]/00_프로젝트_허브/ACTIVE_CONTEXT.md → 최신 main/관련 PR → 원본 코드·자산·검증을 확인해줘.\n이 HTML은 발행 시점의 파생 화면이므로 로컬 원본과 현재 Git 상태를 다시 대조해줘. PR #342 후보와 main을 구분하고 다른 폴더의 미커밋 변경을 보존해줘. output/blueprint/resume-index.json에서 자산·작업의 원본 경로를 찾을 수 있어.\n변경할 부분: \n보호할 부분: 게임 규칙·저장 호환성·승인 원화·기존 PDF·다른 작업 폴더.\n이미 완료된 작업은 재수행하지 말고, 미검증을 완료로 표시하지 말아줘.`;}
function resume(){return title('CONTINUE WITH CONTEXT','다음 작업 이어가기','같은 로컬 원본을 확인할 수 있는 다른 채팅·AI에게 현재 위치와 보호 범위를 전달합니다.')+`<div class="notice">HTML은 ${E(D.generated_at)}에 생성한 화면입니다. 이후 변경은 자동 반영되지 않습니다. 외부 AI가 이 PC의 파일에 접근할 수 없다면 사용자가 필요한 자료를 전달해야 합니다.</div><textarea id="resume-text" aria-label="재개 요청 문구">${E(resumeText())}</textarea><p><button id="resume-copy-body">재개 요청 복사</button></p><h2>다음 작업자가 먼저 확인할 것</h2><ol><li>현재 규칙·Active Context·최신 main·관련 PR을 다시 확인한다.</li><li>대상의 같은 ID로 기획·승인 자산·사용처·검증·잔여 작업을 대조한다.</li><li>미커밋 변경과 다른 작업 폴더를 보존한다.</li><li>작업 후 기존 기록에 누적하고 HTML을 재생성한다.</li></ol><div class="links">${link('AGENTS.md','작업 규칙')}${link('[기획서]/00_프로젝트_허브/ACTIVE_CONTEXT.md','재개 지점')}<a href="resume-index.json">AI용 파생 인덱스 ↗</a><a href="manifest.json">입력 해시·내용 목록 ↗</a></div><h2>발행 상태</h2>${raw({branch:D.branch,revision:D.source_revision,dirty_paths:D.dirty_paths,github_observed_at:D.pm.github.observed_at},'기준 버전과 당시 미커밋 파일')}<p>재생성 방법: 저장소에서 <code>python tools/build_html_blueprint.py</code> 실행. 원본 파일 누락·승인 해시 불일치가 있으면 기존 정상 HTML을 유지합니다.</p>`;}
function missing(text='항목을 찾을 수 없습니다.'){return `<div class="empty">${E(text)} <a href="#home">전체 보기</a></div>`;}
function maps(id,focus){const g=D.diagrams.find(d=>d.id===id)||D.diagrams[0],selected=g.nodes.find(n=>n.id===focus),related=g.edges.filter(e=>e.from===focus||e.to===focus);return title('SOURCE-LINKED DIAGRAMS','연결 구조도','흐름·책임·전달 순서를 구분해 읽습니다. 노드를 선택하면 직접 연결과 실제 원본을 확인할 수 있습니다.')+`<div class="row">${D.diagrams.map(d=>`<a class="badge ${d.id===g.id?'':'warn'}" href="#maps/${d.id}">${E(d.title)}</a>`).join('')}</div><h2>${E(g.title)}</h2><div class="notice">${E(g.note)}</div><div class="diagram-viewport"><svg class="diagram" viewBox="0 0 ${g.width} ${g.height}" role="img" aria-label="${E(g.title)}"><defs><marker id="arrowhead" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#9a6b2b"/></marker></defs>${g.kind==='sequence'?g.nodes.map(n=>`<line x1="${n.x+n.w/2}" y1="${n.y+n.h}" x2="${n.x+n.w/2}" y2="${g.height-25}" stroke="#a6b2ae" stroke-dasharray="5 5"/>`).join(''):''}${g.edges.map(e=>`<g class="diagram-edge ${!focus||e.from===focus||e.to===focus?'':'dim'}"><polyline points="${e.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#9a6b2b" stroke-width="${focus&&(e.from===focus||e.to===focus)?4:2}" ${e.variant==='return'?'stroke-dasharray="6 4"':''} marker-end="url(#arrowhead)"/><text x="${e.label_at[0]}" y="${e.label_at[1]}" text-anchor="middle" class="edge-label">${E(e.label)}</text></g>`).join('')}${g.nodes.map(n=>`<a href="#maps/${g.id}/${n.id}" aria-label="${E(n.label)} 원본과 직접 연결 확인"><rect x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="10" fill="${n.id===focus?'#173337':'#fffdf8'}" stroke="${n.id===focus?'#9a6b2b':'#aaa18d'}" stroke-width="2"/><text x="${n.x+n.w/2}" y="${n.y+42}" fill="${n.id===focus?'#f3dfb3':'#172c30'}" text-anchor="middle" font-size="20" font-weight="700">${E(n.label)}</text><text x="${n.x+n.w/2}" y="${n.y+67}" fill="${n.id===focus?'#d7dfd5':'#64716c'}" text-anchor="middle" font-size="12">선택하여 원본 확인</text></a>`).join('')}</svg></div>${selected?`<section class="panel"><h3>${E(selected.label)}</h3><p>${E(selected.detail)}</p><div class="links">${selected.sources.map(p=>link(p,'실제 원본 · '+p.split('/').pop())).join('')}<a href="#maps/${g.id}">강조 해제</a></div>${table(['직접 연결','의미'],related.map(e=>[g.nodes.find(n=>n.id===e.from).label+' → '+g.nodes.find(n=>n.id===e.to).label,e.label]))}<p><button data-request="diagram:${E(g.id)}/${E(selected.id)}">이 구조의 수정 요청 복사</button></p></section>`:'<p>상자를 선택하거나 키보드 Tab으로 이동한 뒤 Enter를 누르세요. 화살표의 의미와 방향은 원본 설명을 따릅니다.</p>'}<details><summary>구조도 원본·검증 범위</summary><p>Archify의 안정적인 ID·명시적 관계·원본 근거·정적 의미 보존 방식을 참고한 프로젝트 전용 SVG입니다. Archify 렌더러나 Showcase 검사를 실행했다고 주장하지 않습니다. 노드 겹침·영역 이탈·없는 대상·다른 노드를 가로지르는 연결을 자동 검사합니다.</p>${link('tools/html_blueprint_diagrams.py','구조도 표시 원본')}</details>`;}
function render(){clearInterval(motionTimer);motionTimer=null;const [section='maps',id,focus]=decodeURIComponent(location.hash.slice(1)||'maps').split('/');document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===(section==='asset'?'assets':section);a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});main.innerHTML=({home:()=>home(),reader:()=>reader(id),people:()=>people(id),assets,asset:()=>asset(id),maps:()=>maps(id,focus),motion:()=>title('RECORDED GODOT PRESENTATION','격돌 · 합 · 카드 연출')+movies('motion',id?[id]:null),pm:()=>pm(id),evidence,resume}[section]??(()=>missing()))();bind();if(section==='asset'&&byId(id)?.grid)motion(byId(id));}
let tableResizeObserver=null;
function updateScrollableTables(tables){
 const measured=[...tables].map(el=>({el,overflow:el.clientWidth>0&&el.scrollWidth>el.clientWidth+1}));
 for(const {el,overflow} of measured){el.dataset.scrollable=String(overflow);
  if(overflow){const label=el.querySelector('caption')?.textContent||el.closest('section,article')?.querySelector('h2,h3')?.textContent||el.querySelector('thead')?.textContent||'표';el.setAttribute('tabindex','0');el.setAttribute('role','region');el.setAttribute('aria-label',label.trim()+' · 좌우 방향키로 전체 열 읽기');}
  else {el.removeAttribute('tabindex');el.removeAttribute('role');el.removeAttribute('aria-label');}
 }
}
function bindScrollableTables(){
 tableResizeObserver?.disconnect();const tables=document.querySelectorAll('#main .table-wrap');updateScrollableTables(tables);
 if(typeof ResizeObserver==='function'){tableResizeObserver=new ResizeObserver(entries=>updateScrollableTables(entries.map(e=>e.target)));for(const table of tables)tableResizeObserver.observe(table);}
}
window.addEventListener('resize',()=>{if(typeof ResizeObserver!=='function')updateScrollableTables(document.querySelectorAll('#main .table-wrap'));});
function bind(){bindScrollableTables();document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{const img=document.createElement('img');img.src=b.dataset.image;img.alt='원본 이미지 확대';const body=document.getElementById('viewer-body');body.replaceChildren(img);document.getElementById('viewer').showModal();});document.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>copy(resumeText(b.dataset.request)));document.getElementById('asset-filter')?.addEventListener('change',e=>{assetFilter=e.target.value;render();});document.getElementById('asset-category')?.addEventListener('change',e=>{assetCategory=e.target.value;render();});document.getElementById('resume-copy-body')?.addEventListener('click',()=>copy(document.getElementById('resume-text').value));}
function motion(a){const canvas=document.getElementById('motion'),ctx=canvas.getContext('2d'),im=new Image(),slider=document.getElementById('motion-frame');let index=0,seq=0;const [cols,rows]=a.grid;function draw(){if(!canvas.isConnected||!im.complete||!im.naturalWidth)return;const w=im.naturalWidth/cols,h=im.naturalHeight/rows;canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);ctx.drawImage(im,(index%cols)*w,Math.floor(index/cols)*h,w,h,0,0,w,h);document.getElementById('frame-label').textContent=`포즈 ${index+1} / ${cols*rows}`;slider.value=index;}function stop(){clearInterval(motionTimer);motionTimer=null;if(document.getElementById('motion-play'))document.getElementById('motion-play').textContent='재생';}im.onload=draw;im.src=a.url;slider.oninput=()=>{stop();index=Number(slider.value);draw();};document.getElementById('motion-prev').onclick=()=>{stop();index=(index-1+cols*rows)%(cols*rows);draw();};document.getElementById('motion-next').onclick=()=>{stop();index=(index+1)%(cols*rows);draw();};const play=document.getElementById('motion-play');if(play)play.onclick=()=>{if(motionTimer){stop();return;}play.textContent='정지';motionTimer=setInterval(()=>{index=a.sequence[seq++%a.sequence.length];draw();},250/Number(document.getElementById('motion-speed').value));};document.getElementById('motion-speed')?.addEventListener('change',stop);}
async function copy(text){try{await navigator.clipboard.writeText(text);document.getElementById('notice').textContent='재개 요청을 복사했습니다.';setTimeout(()=>document.getElementById('notice').textContent='',2600);}catch{location.hash='resume';setTimeout(()=>{const t=document.getElementById('resume-text');if(t){t.value=text;t.focus();t.select();document.getElementById('notice').textContent='복사가 제한된 환경입니다. 선택된 문구를 직접 복사하세요.';}},0);}}
document.getElementById('skip-content').onclick=e=>{e.preventDefault();main.focus();};
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInterval(motionTimer);motionTimer=null;const p=document.getElementById('motion-play');if(p)p.textContent='재생';}});
document.getElementById('close-viewer').onclick=()=>document.getElementById('viewer').close();
document.getElementById('resume-copy').onclick=()=>copy(resumeText());
search.oninput=()=>{if(!['reader','assets','people','pm'].includes(location.hash.slice(1).split('/')[0]))location.hash='assets';else render();};
function followLocation(){const [section,id,focus]=decodeURIComponent(location.hash.slice(1)).split('/');const target=section==='maps'&&focus?'stage-detail':section==='home'&&id?'overview-'+id:null;if(target){const node=document.getElementById(target);node?.scrollIntoView({behavior:'instant',block:'start'});if(section==='maps')node?.focus({preventScroll:true});}else window.scrollTo(0,0);}
window.addEventListener('hashchange',()=>{render();followLocation();});
render();
