/* Current design is derived from the existing GDD and structured SWOT owners. */
function designDocument(){
 const sections=D.current_design.split(/^### /m).filter(s=>s.trim());
 return `<section class="current-design"><div class="eyebrow">현재 게임 기획서</div><h2>십보강호 · 읽고, 겨루고, 기연으로 달라지는 여정</h2>${sections.map(s=>{const lines=s.trim().split('\n');return `<section class="panel"><h3>${E(lines.shift())}</h3>${lines.filter(x=>x.trim()).map(p=>`<p>${E(p)}</p>`).join('')}</section>`;}).join('')}<h2>상세 SWOT · 대상과 매력, 예상 문제와 대응</h2>${D.current_swot.map(s=>`<section class="panel"><h3>${E(s.title)}</h3>${table(['관점','내용'],[['대상',s.target],['재미·메리트',s.merit],['현재 근거',s.evidence],['예상 문제',s.problem],['개발 대응',s.action],['검증 기준',s.acceptance],['남은 위험',s.risk]])}</section>`).join('')}<div class="links">${link('docs/01_GAME_DESIGN.md','기획서 원본')}${link('docs/blueprint/IMPLEMENTATION_READINESS.json','SWOT 원본')}<a href="#maps/game-loop/route">강호행로 화면</a><a href="#home/manuals">무공 성장·기술 표</a><a href="#pm">구현과 남은 검증</a></div></section>`;
}
function manualTables(m){const t=m.readable_tables;return t?`<section class="manual-tables"><h3>성수별 성장 효과</h3><p>각 행은 그 성수에서 새로 생기는 변화입니다. 앞서 해금한 기술·조건 효과는 유지됩니다. 기획의 능력치 보너스와 현재 main 지급 여부를 구분합니다. PR #342의 성장 확장은 별도 후보입니다.</p>${table(['성수','이전 성수에서의 추가 비용','해금·강화 효과','조건·능력치','현재 연결 상태'],t.growth)}<h3>기술의 비용·거리·처리 순서</h3><p>기본 기술 효과입니다. 5·9성의 추가 조건 효과는 위 성장표를 함께 보세요. 조건을 충족하지 못하면 뒤의 타격이 발생하지 않을 수 있습니다.</p>${table(['기술','해금','소모 수','자원','거리','순서와 조건'],t.techniques)}</section>`:'';}
const designReader=reader,designExplanation=explanation,designManualCatalog=manualCatalog;
reader=function(id){return id==='reader-001'?designDocument()+`<details><summary>기존 승인 소개와 원래 배치</summary>${designReader(id)}</details>`:designReader(id);};
explanation=function(id,prefix='explain'){return id==='reader-001'?`<article class="scroll-chapter" id="${E(prefix+'-'+id)}" data-reader="${E(id)}">${designDocument()}<details><summary>기존 승인 소개와 원래 배치</summary>${designExplanation(id,prefix+'-history')}</details></article>`:designExplanation(id,prefix);};
manualCatalog=function(prefix='manual',focus=null){return designManualCatalog(prefix,focus).replace(/(<section class="panel" data-manual="([^"]+)">)/g,(all,opening,id)=>opening+manualTables(D.manuals.find(m=>m.manual_id===id)));};
const designBind=bind;
bind=function(){designBind();document.querySelectorAll('img').forEach(img=>{
 function failed(){const target=img.closest('a,button')||img;if(!img.isConnected||target.nextElementSibling?.classList.contains('media-recovery'))return;const message=document.createElement('span');message.className='notice media-recovery';message.textContent='이미지를 불러오지 못했습니다. 프로젝트의 「블루프린트 열기」를 실행해 현재 발행본을 다시 여세요. ';const retry=document.createElement('button');retry.type='button';retry.textContent='다시 불러오기';retry.onclick=event=>{event.preventDefault();event.stopPropagation();message.remove();const url=new URL(img.src);url.searchParams.set('retry',String(Date.now()));img.src=url.href;};message.append(retry);target.insertAdjacentElement('afterend',message);}
 img.addEventListener('error',failed);if(img.complete&&!img.naturalWidth)failed();
 });};
document.getElementById('freshness').insertAdjacentHTML('afterend','<details class="preview-help"><summary>다음에 다시 열기 · 접속 문제</summary><p>프로젝트 폴더의 「블루프린트 열기.cmd」를 실행하면 현재 발행본과 서버를 확인하고 외부 브라우저로 엽니다. 서버가 종료되면 오래된 주소 대신 이 파일을 다시 실행하세요. AI는 tools/open_html_blueprint.py --no-open으로 현재 주소를 얻습니다. 같은 PC에서만 연결되며 클라우드 AI는 별도 접근 환경이 필요합니다.</p></details>');

function giyunCatalog(focus=null){return `<section class="giyun-catalog"><h2>기연 · 이번 여정의 빌드를 바꾸는 만남</h2><p>기연은 회차 한정으로 자동 적용됩니다. 같은 기연은 중복 획득하지 않으며 보유한 비결을 다시 받으면 표시된 수련 보상으로 전환됩니다. 아래는 실제 게임 데이터의 설명입니다. 사람 재미 검증과 개별 연출 촬영은 별도입니다.</p><details><summary>실제 Godot 사건 화면 · 6개 보유 검수 상황</summary><img loading="lazy" src="${E(src(D.giyun_capture))}" alt="실제 Godot 사건 선택 화면"><p>2026-09-23 실제 렌더 960×600. 보유6개·사건3선택 fixture이며 실제 캠페인 승리나 사람 재미 검증이 아닙니다.</p></details><div class="grid">${D.giyun.giyun.filter(g=>!focus||g.id===focus).map(g=>`<article class="card"><h3>${E(g.name)}</h3><p>${E(g.description)}</p><p><small>${E(g.limit)}</small></p>${recordControls(recordById('giyun:'+g.id))}<a href="#giyun/${E(g.id)}">이 기연과 획득 사건만 보기 →</a></article>`).join('')}</div><h3>무림의 사건과 선택</h3>${D.giyun.events.filter(e=>!focus||e.giyun_id===focus).map(e=>`<article class="panel"><h3>${E(e.title)}</h3><p>${E(e.text)}</p>${table(['선택','대가와 결과'],[['힘을 보태고 비결 받기','체력 -'+e.health_cost+' · '+D.giyun.giyun.find(g=>g.id===e.giyun_id).name+' 획득 / 이미 보유 시 자유 수련 +3'],['이야기에서 배우기','자유 수련 +2'],['길을 가기','기력 +1']])}<p>체력이 대가 이하이면 첫 선택을 할 수 없습니다. 사건과 결과는 이어하기로 다시 추첨되지 않습니다.</p></article>`).join('')}<div class="links">${link('data/run/giyun_rules.json','기연·사건 데이터')}${link('src/run/giyun_rules.gd','발동 규칙')}${link('docs/decisions/2026-09-23_GIYUN_DDD_BLUEPRINT.md','승인 범위와 검증 기록')}<a href="#maps/game-loop/route">강호행로로 돌아가기</a><a href="#home/manuals">조합할 무공 보기</a></div></section>`;}
const giyunStagePanel=stagePanel,giyunHome=home;
stagePanel=function(id){return giyunStagePanel(id)+(id==='route'?giyunCatalog():'');};
home=function(){return giyunHome()+`<section id="overview-giyun">${giyunCatalog()}</section>`;};
document.getElementById('nav').innerHTML+='<a href="#giyun" data-nav="giyun">기연 · 사건</a>';
