/* Current design is derived from the existing GDD and structured SWOT owners. */
function designDocument(){
 const sections=D.current_design.split(/^### /m).filter(s=>s.trim());
 return `<section class="current-design"><div class="eyebrow">현재 게임 기획서</div><h2>십보강호 · 읽고, 겨루고, 기연으로 달라지는 여정</h2>${sections.map(s=>{const lines=s.trim().split('\n');return `<section class="panel"><h3>${E(lines.shift())}</h3>${lines.filter(x=>x.trim()).map(p=>`<p>${E(p)}</p>`).join('')}</section>`;}).join('')}<h2>상세 SWOT · 대상과 매력, 예상 문제와 대응</h2>${D.current_swot.map(s=>`<section class="panel"><h3>${E(s.title)}</h3>${table(['관점','내용'],[['대상',s.target],['재미·메리트',s.merit],['현재 근거',s.evidence],['예상 문제',s.problem],['개발 대응',s.action],['검증 기준',s.acceptance],['남은 위험',s.risk]])}</section>`).join('')}<div class="links">${link('docs/01_GAME_DESIGN.md','기획서 원본')}${link('docs/blueprint/IMPLEMENTATION_READINESS.json','SWOT 원본')}<a href="#maps/game-loop/route">강호행로 화면</a><a href="#home/manuals">무공 성장·기술 표</a><a href="#pm">구현과 남은 검증</a></div></section>`;
}
function commonGrowthTable(){const rows=D.manuals[0]?.readable_tables?.shared_growth;return rows?`<section class="common-growth panel" data-common-growth><h3>성수별 성장 효과 · 모든 무공 공용</h3><p>기술 획득은3·7·10성, 추가 효과는5·9성입니다. 앞서 얻은 기술과 효과는 유지되며 각 무공의 구체적인 효과는 아래 기술표에 표시합니다. 능력치 증가의 기획과 현재 지급 여부는 구분합니다.</p>${table(['성수','이전 성수에서의 추가 비용','기술 획득·강화','현재 연결 상태'],rows)}</section>`:'';}
function manualTables(m){const t=m.readable_tables;if(!t)return '';const pictures=D.art_selection.manuals[m.manual_id]??[];const effects=rows=>`<ol>${rows.map(x=>`<li>${E(x)}</li>`).join('')}</ol>`;return `<section class="manual-tables"><p class="manual-summary"><strong>${E(m.faction??'')} · ${E(m.manual_name??m.name)}</strong> · 주 능력치 ${E(m.primary_stat)} · 보조 능력치 ${E(m.secondary_stat)} · 절초 ${E(t.card_rows[2].name)}</p><div class="table-wrap"><table class="technique-table"><thead><tr><th scope="col">삽화 · 기술</th><th scope="col">소모·거리 / 기본 효과 순서</th><th scope="col">추가 효과 · 연출</th></tr></thead><tbody>${t.card_rows.map((row,i)=>{const c=Object.values(m.cards).find(c=>c.id===row.id),a=D.assets.find(a=>a.path===D.art_selection.directory+'/'+pictures[i]),number=a?imageRowForAsset(a):null,clip=D.experience.clips.find(v=>v.id===row.id);return `<tr data-card="${E(row.id)}"><td class="technique-art"><h3>${row.unlock_star===10?'10성 · 절초':row.unlock_star+'성 기술'} · ${E(row.name)}</h3>${a?`<div data-numbered-image="${E(a.id)}"><button class="media-button" data-image="${E(a.url)}" aria-label="${E(row.name)} 삽화 확대"><img loading="lazy" ${previewImageAttributes(a.url,'(max-width:1100px) 220px, 28vw')} alt="${E(row.name)} 삽화"></button>${number?imageCaption(number):''}<small>삽화 상태·코멘트</small>${userReviewPanel(recordById('asset:'+a.id))}</div>`:'<p>연결된 삽화 없음</p>'}</td><td><p><strong>${E(c.action_slots)}수 · 기력 ${E(c.stamina_cost??0)} · 내력 ${E(c.internal_cost??0)} · 거리 ${E(c.range?c.range.min+'~'+c.range.max:'—')}</strong></p>${effects(row.effects)}${raw(c,'기술 효과 · 원본 데이터')}</td><td>${row.enhancement?`<p><strong>${row.enhancement.unlock_star}성 추가 효과 · ${E(row.enhancement.name)}</strong></p>${effects(row.enhancement.effects)}`:'<p>절초 획득 · 별도 성수 추가 효과 없음</p>'}${clip?`<a class="play-link" href="#motion/${E(clip.id)}">▶ ${E(row.name)} 연출 보기</a><p><small>실제 Godot 촬영 ${E(clip.duration_seconds)}초 · ${E(clip.outcomes.join(' / '))}</small></p>`:'<p>해당 기술의 촬영 근거 없음</p>'}<a href="#inspect/${E('card:'+row.id)}">기술 구현·검수 근거</a><p><small>기술 상태·코멘트</small></p>${userReviewPanel(recordById('card:'+row.id))}</td></tr>`;}).join('')}</tbody></table></div></section>`;}
const designReader=reader,designExplanation=explanation;
reader=function(id){return id==='reader-001'?designDocument()+`<details><summary>기존 승인 소개와 원래 배치</summary>${designReader(id)}</details>`:designReader(id);};
explanation=function(id,prefix='explain'){return id==='reader-001'?`<article class="scroll-chapter" id="${E(prefix+'-'+id)}" data-reader="${E(id)}">${designDocument()}<details><summary>기존 승인 소개와 원래 배치</summary>${designExplanation(id,prefix+'-history')}</details></article>`:designExplanation(id,prefix);};
const designBind=bind;
bind=function(){designBind();document.querySelectorAll('img').forEach(img=>{
 function failed(){if(img.style)img.style.visibility='hidden';const target=img.closest('.sprite-window')||img.closest('a,button')||img;if(!img.isConnected||target.nextElementSibling?.classList.contains('media-recovery'))return;const message=document.createElement('span');message.className='notice media-recovery';message.textContent='이미지를 불러오지 못했습니다. 프로젝트의 「블루프린트 열기」를 실행해 현재 발행본을 다시 여세요. ';const retry=document.createElement('button');retry.type='button';retry.textContent='다시 불러오기';retry.onclick=event=>{event.preventDefault();event.stopPropagation();message.remove();const url=new URL(img.src);url.searchParams.set('retry',String(Date.now()));img.src=url.href;};message.append(retry);target.insertAdjacentElement('afterend',message);}
 img.addEventListener('load',()=>{if(img.style)img.style.visibility='';});img.addEventListener('error',failed);if(img.complete&&!img.naturalWidth)failed();
 });};
document.getElementById('freshness').insertAdjacentHTML('afterend','<details class="preview-help"><summary>다음에 다시 열기 · 접속 문제</summary><p>프로젝트 폴더의 「블루프린트 열기.cmd」를 실행하면 현재 발행본과 서버를 확인하고 외부 브라우저로 엽니다. 서버가 종료되면 오래된 주소 대신 이 파일을 다시 실행하세요. AI는 tools/open_html_blueprint.py --no-open으로 현재 주소를 얻습니다. 같은 PC에서만 연결되며 클라우드 AI는 별도 접근 환경이 필요합니다.</p></details>');

function giyunCatalog(focus=null){return `<section class="giyun-catalog"><h2>기연 · 이번 여정의 빌드를 바꾸는 만남</h2><p>기연은 일부 사건의 특정 선택이 성공한 뒤 낮은 확률로 얻습니다. 일반 사건과 안전 선택은 기연을 주지 않습니다. 회차 한정으로 자동 적용되며, 이미 보유한 기연에 다시 당첨되면 추가 수련으로 바뀝니다.</p><details><summary>이전 규칙v1의 Godot 검수 기록</summary><img loading="lazy" src="${E(src(D.giyun_capture))}" width="960" height="600" alt="2026-09-23 기연v1 사건 선택 검수 화면"><p>2026-09-23 실제 렌더. 보유6개·사건3선택 fixture입니다. 현재 확률 판정이나 실제 캠페인·사람 재미 검증을 보여 주는 화면은 아닙니다.</p></details><div class="grid">${D.giyun.giyun.filter(g=>!focus||g.id===focus).map(g=>`<article class="card"><h3>${E(g.name)}</h3><p>${E(g.description)}</p><p><small>${E(g.limit)}</small></p>${recordControls(recordById('giyun:'+g.id))}<a href="#giyun/${E(g.id)}">이 기연과 획득 가능한 사건만 보기 →</a></article>`).join('')}</div><h3>무림의 사건과 선택</h3>${focus?eventCatalogView(D.pages.find(p=>p.id==='reader-011').blocks[0],focus):'<p>일반 사건과 희귀 기연 사건의 상황·선택지·성공/실패 결과는 아래 사건 목록에 모았습니다.</p>'}<a href="#reader/reader-011">사건별 상황·선택 결과 보기 →</a><div class="links">${link('data/run/giyun_rules.json','기연·사건 데이터')}${link('src/run/jianghu_event_checks.gd','능력치·희귀 보상 판정')}${link('docs/decisions/2026-09-24_EVENT_CHECKS_AND_HTML_READABILITY.md','승인한 규칙과 의도')}<a href="#maps/game-loop/route">강호행로로 돌아가기</a><a href="#home/manuals">조합할 무공 보기</a></div></section>`;}
const giyunStagePanel=stagePanel;
stagePanel=function(id){return giyunStagePanel(id)+(id==='route'?giyunCatalog():'');};
document.getElementById('nav').innerHTML+='<a href="#giyun" data-nav="giyun">기연 · 사건</a>';

// Keep a locally open reader alive; never reload a user's draft or scroll position.
if(location.protocol==='http:' && /^\/p\/[^/]+\//.test(location.pathname)){
 const sessionURL=location.pathname.match(/^\/p\/[^/]+\//)[0]+'_session';
 document.getElementById('main').insertAdjacentHTML('beforebegin','<div id="preview-status" class="preview-status" role="status" hidden></div>');
 document.getElementById('freshness').insertAdjacentHTML('beforeend','<br><span id="preview-health">미디어 연결 확인 중</span>');
 let checkingSession=false;
 async function checkPreviewSession(){if(checkingSession||document.visibilityState==='hidden')return;checkingSession=true;const banner=document.getElementById('preview-status'),status=document.getElementById('preview-health');try{
  const response=await fetch(sessionURL,{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error('session unavailable');const session=await response.json();
  if(session.state==='SUPERSEDED'){status.textContent='새 발행본 있음';banner.hidden=false;banner.innerHTML='새 발행본이 준비되어 일부 이전 이미지·영상이 바뀌었습니다. '+(session.latest_url?`<a href="${E(session.latest_url+location.hash)}" target="_blank" rel="noopener">새 발행본 열기 ↗</a>`:'「블루프린트 열기.cmd」를 다시 실행해 주세요.');}
  else{status.textContent='미디어 연결 정상 · 읽는 동안 유지';banner.hidden=true;banner.textContent='';}
 }catch{status.textContent='미디어 연결 끊김';banner.hidden=false;banner.textContent='이미지·영상 서버 연결이 끊겼습니다. 프로젝트의 「블루프린트 열기.cmd」를 실행해 새 주소로 여세요. 작성 중인 코멘트는 이 창에 유지됩니다.';}finally{checkingSession=false;}}
 checkPreviewSession();setInterval(checkPreviewSession,60000);document.addEventListener('visibilitychange',checkPreviewSession);
}
