/* Source-derived descriptions only. All success/rare rolls belong to Godot. */
function eventCatalogView(block, focus=null){
 const rule=block.chance_rule, events=block.events.filter(e=>!focus||e.choices.some(c=>c.giyun_id===focus));
 return `<section class="event-catalog"><div class="event-rules"><h3>능력치로 도전하고, 기연은 드물게</h3><p>기연이 없는 일반 사건도 있습니다. 기연이 표시된 선택은 <strong>성공한 뒤 추가 ${E(rule.rare_after_success)}%</strong> 확률로만 얻습니다. 성공률60%인 선택이라면 최종 기연 확률은6%입니다.</p><details><summary>성공률 계산과 저장 규칙</summary><p>기본 ${E(rule.base)}% + (관련 능력치 − 난도) × ${E(rule.per_stat)}%p. 최소 ${E(rule.minimum)}%, 최대 ${E(rule.maximum)}%입니다. 안전한 떠나기는 판정·보상·손실이 없습니다.</p><p>실제 플레이어 능력치와 성공률은 게임의 선택 화면에서 확인합니다. 이 문서는 사건 목록이며 현재 플레이 중인 저장 상태를 읽지 않습니다. 현재 전투 시작 능력치는 다섯 항목 모두4이고, 능력치 성장 후보는 별도 작업입니다. 결과는 회차·사건·선택지에 고정되어 이어하기로 다시 추첨되지 않습니다.</p></details></div>${events.map((event,index)=>{
 const rare=event.choices.some(c=>c.giyun_id);
 return `<article class="event-card" data-event-id="${E(event.id)}"><header class="event-heading"><span class="event-number">사건 ${index+1}</span><h3>${E(event.title)}</h3><span class="badge ${rare?'':'neutral'}">${rare?'일부 선택에 희귀 기연':'일반 사건 · 기연 없음'}</span></header><p class="event-situation">${E(event.text)}</p><div class="table-wrap event-choices"><table><caption class="sr-only">${E(event.title)} · 세 선택지의 결과</caption><thead><tr><th scope="col">선택</th><th scope="col">능력치 판정</th><th scope="col">성공하면</th><th scope="col">실패하면</th><th scope="col">추가 기연</th></tr></thead><tbody>${event.choices.map((choice,i)=>`<tr class="${choice.giyun_id?'rare-choice':''}"><th scope="row"><span class="choice-number">${i+1}</span>${E(choice.label)}</th><td>${E(choice.check_text)}</td><td>${E(choice.success_text)}</td><td>${E(choice.failure_text)}</td><td>${E(choice.rare_text)}${choice.giyun_id?`<br><a href="#giyun/${E(choice.giyun_id)}">기연 효과 보기 →</a>`:''}</td></tr>`).join('')}</tbody></table></div></article>`;
 }).join('')}</section>`;
}
const eventReaderBlock=block;
block=function(item){return item.kind==='event_catalog'?eventCatalogView(item):eventReaderBlock(item);};
