/* Atlas boxes are the navigation. All mechanics remain owned by Godot/data. */
const originalMaps=maps, originalHome=home, originalAssets=assets, originalEvidence=evidence;
function movie(clip, prefix='clip'){
 const id=prefix+'-'+clip.id;
 return `<article class="movie card" data-clip="${E(clip.id)}"><h3>${E(clip.title)}</h3>
 <video id="${E(id)}" controls playsinline preload="none" poster="${E(src(clip.poster))}" aria-label="${E(clip.title)} 연출 영상"><source src="${E(src(clip.path))}" type="video/mp4"><a href="${E(src(clip.path))}">영상 직접 열기</a></video>
 <div class="row"><button data-video="${E(id)}">재생 / 일시정지</button><label>배속 <select data-video-speed="${E(id)}"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label><a href="${E(src(clip.path))}" target="_blank" rel="noopener">MP4 열기 ↗</a></div>
 <p><small>현재 main 계열 · 실제 Godot 장면 촬영 · ${E(clip.duration_seconds)}초 · 음성 미포함<br>관측 결과: ${E(clip.outcomes.join(' / '))} · 기준 ${E(clip.source_revision.slice(0,10))}</small></p>${clip.visual_status==='STATIC_OR_EFFECT_ONLY'?'<div class="notice">이 상황은 현재 main에서 정적 결과 표시 위주입니다. 고유 캐릭터 움직임이 구현됐다고 표시하지 않습니다.</div>':''}
 <details><summary>촬영 상황과 원본 연결</summary><p>고정 상황의 연출 확인용입니다. 캠페인 플레이·재미·PR #342 검증과 구분합니다. 같은 동작을 공유하는 기술은 영상에서도 그대로 보입니다.</p>${raw(clip.events,'Godot에 전달된 실제 이벤트')}${link('docs/blueprint/evidence/motion/manifest.json','촬영 시점·파일·사용처 근거')}${link('src/combat/combat_board_preview.gd','Godot 연출 구현')}</details></article>`;
}
function movies(prefix='movies', ids=null){const clips=D.experience.clips.filter(c=>!ids||ids.includes(c.id));return `<div class="notice">Godot에서 직접 촬영한 움직임입니다. 기본 6개는 고정된 결과 상황, 무공 30개는 공유 판정 코어가 만든 이벤트를 재생합니다. 실패·조건 미충족 결과도 숨기지 않습니다. PR #342의 추가 연출은 미병합 후보입니다.</div><div class="movies">${clips.map(c=>movie(c,prefix)).join('')}</div>`;}
function cardSummary(card){return `<p>${E(({attack:'공격',response:'대응',recovery:'회복',move:'이동',movement:'이동',support:'보조',observation:'관찰',strengthen:'강화'})[card.category]??card.category)} · ${E(card.action_slots)}수 · 기력 ${E(card.stamina_cost??0)} · 내력 ${E(card.internal_cost??0)} · 거리 ${E(card.range?card.range.min+'~'+card.range.max:(card.range_text??'—'))}</p>${card.effect_text?'<p>'+E(card.effect_text)+'</p>':''}${(card.effect_descriptions??[]).map(t=>'<p>'+E(t)+'</p>').join('')}${raw(card.effect_steps??card.effects??card,'효과와 발동 조건 · 원본 데이터')}`;}
function basicActionCards(start=0,count=10){const shared=D.image_catalog.find(r=>r.path===D.experience.actions[0].illustration.path);return `<section class="basic-actions"><h3>배치할 수 있는 기초 행동</h3><div class="basic-action-grid">${D.experience.actions.slice(start,start+count).map(a=>{const art=a.illustration,row=D.image_catalog.find(r=>r.path===art.path);return `<article class="card basic-action" data-basic-action="${E(a.id)}"><figure data-numbered-image="${E(art.path)}"><svg viewBox="${art.region.join(' ')}" role="img" aria-label="${E(a.name)} · 게임에서 사용하는 삽화"><svg x="${art.region[0]}" y="${art.region[1]}" width="${art.region[2]}" height="${art.region[3]}" viewBox="${art.region.join(' ')}" overflow="hidden"><image href="${E(src(art.path))}" width="${art.size[0]}" height="${art.size[1]}"/></svg></svg><figcaption>전투 · 이미지 ${row?.number??'—'} · ${E(a.name)} 삽화</figcaption></figure><h3>${E(a.name)}</h3>${cardSummary(a)}</article>`;}).join('')}</div><p>삽화는 게임에서 사용하는 같은 이미지 19의 영역입니다. 이름·비용·효과는 현재 게임 데이터에서 표시합니다.</p>${shared?userReviewPanel(recordById(shared.record_id)):''}</section>`;}
function manualCatalog(prefix='manual', focus=null){return `<div class="manuals">${D.manuals.filter(m=>!focus||m.manual_id===focus).map(m=>`<section class="panel" data-manual="${E(m.manual_id)}"><h2>${E(m.manual_name??m.name)}</h2><p>주 능력치 ${E(m.primary_stat)} · 보조 능력치 ${E(m.secondary_stat)}</p><div class="gallery">${(D.art_selection.manuals[m.manual_id]??[]).map(p=>D.assets.find(a=>a.path===D.art_selection.directory+'/'+p)).filter(Boolean).map(tile).join('')}</div><div class="manual-cards">${Object.values(m.cards).map(c=>{const clip=D.experience.clips.find(v=>v.id===c.id);return `<article class="card" data-card="${E(c.id)}"><h3>${E(c.unlock_star)}성 · ${E(c.name)}</h3>${cardSummary(c)}${clip?movie(clip,prefix):'<p>이 기술의 촬영 근거 없음</p>'}</article>`;}).join('')}</div>${link('data/cards/martial_manuals/'+m.manual_id+'.json','무공 원본')}</section>`).join('')}</div>`;}
function explanation(id, prefix='explain'){const p=D.pages.find(p=>p.id===id);return p?`<article class="scroll-chapter" id="${E(prefix+'-'+id)}" data-reader="${E(id)}"><h2>${E(p.title)}</h2><p>${E(p.subtitle)}</p><p><small>승인 기획 본문 · 당시 상태 ${E(p.historical_state)} · 현재 실행 검증과 구분</small></p>${p.blocks.filter(b=>!(id==='reader-017'&&prefix==='stage'&&b.kind==='basic_actions')).map(block).join('')}<details><summary>승인 당시 페이지와 배치 보기</summary><button class="media-button" data-image="${E(p.approved_page.url)}"><img loading="lazy" src="${E(p.approved_page.url)}" alt="승인 당시 ${E(p.title)} 페이지"></button></details><a href="#reader/${E(id)}">이 설명만 열기 →</a></article>`:'';}
function stagePanel(id){const c=D.experience.contexts[id];if(!c)return '';const node=D.diagrams[0].nodes.find(n=>n.id===id);const tasks=D.pm.items.filter(t=>(t.actual_consumers??[]).some(p=>node.sources.includes(p)));
 return `<section id="stage-detail" tabindex="-1" class="stage-detail"><div class="eyebrow">화면에서 이어서 확인</div><h2>${E(c.title)}</h2><a href="#maps/game-loop">← 전체 화면 구조로</a>
 ${c.manuals?manualCatalog('stage-manual'):''}
 ${c.constraints?`<h3>비무 제약 · 공개 정보</h3>${table(['이름','효과','선택 비용'],D.experience.constraints.constraints.map(x=>[x.display_name_ko,x.effect_summary_ko,x.selection_cost]))}${link('data/run/bimu_constraints.json','제약 원본')}<h3>상대별 정보와 무공</h3>${people(null,true)}`:''}
 ${c.actions?basicActionCards():''}
 ${c.clips?movies('stage'):''}
 <div class="links">${node.sources.map(p=>link(p,"이 화면의 실제 구현" )).join('')}</div>${tasks.length?'<h3>연결된 작업</h3>'+tasks.map(t=>'<p><a href="#pm/'+E(t.work_item_id)+'">'+E(t.title??t.work_item_id)+'</a></p>').join(''):''}<h3>화면·규칙 설명과 아틀라스</h3>${c.pages.map(p=>explanation(p,'stage')).join('')}
 <nav class="stage-next" aria-label="다음 화면">${c.next.map(n=>`<a href="#maps/game-loop/${E(n)}">${E(D.experience.contexts[n].title)} · 다음 화면 →</a>`).join('')}</nav><p><a href="#pm">관련 구현·잔여 작업 확인</a> · <a href="#evidence">실행·검수 근거 확인</a></p></section>`;
}
function atlasPreview(preview,x,y,width,height){
 if(!preview.region)return `<image href="${E(src(preview.path))}" x="${x}" y="${y}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid meet"/>`;
 const [rx,ry,rw,rh]=preview.region;
 return `<svg x="${x}" y="${y}" width="${width}" height="${height}" viewBox="${preview.region.join(' ')}" overflow="hidden"><svg x="${rx}" y="${ry}" width="${rw}" height="${rh}" viewBox="${preview.region.join(' ')}" overflow="hidden"><image href="${E(src(preview.path))}" width="${preview.size[0]}" height="${preview.size[1]}"/></svg></svg>`;
}
maps=function(id,focus){const g=D.diagrams.find(d=>d.id===id)||D.diagrams[0];if(g.id!=='game-loop')return originalMaps(id,focus);
 const scale=1.6;
 return title('SCREEN ATLAS · CONNECTED FLOW','화면으로 보는 연결 구조','상자 안의 화면을 누르면 관련 무공·상대·행동·연출과 설명이 이어집니다.')+`<div class="row">${D.diagrams.map(d=>`<a class="badge" href="#maps/${d.id}">${E(d.title)}</a>`).join('')}</div><p>화면 자료는 승인 당시 아틀라스와 과거 실행 화면입니다. 현재 움직임은 합과 해결의 Godot 촬영 영상에서 확인합니다.</p>
 <div class="diagram-viewport"><svg class="diagram atlas-diagram" viewBox="0 0 ${g.width} ${g.height*scale}" role="img" aria-label="화면 아틀라스 연결 구조"><defs><marker id="atlas-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#9a6b2b"/></marker></defs>
 ${g.edges.map(e=>`<g class="diagram-edge"><polyline points="${e.points.map(([x,y])=>x+','+y*scale).join(' ')}" fill="none" stroke="#9a6b2b" stroke-width="2" ${e.variant==='return'?'stroke-dasharray="6 4"':''} marker-end="url(#atlas-arrow)"/><text x="${e.label_at[0]}" y="${e.label_at[1]*scale}" text-anchor="middle" class="edge-label">${E(e.label)}</text></g>`).join('')}
 ${g.nodes.map(n=>{const c=D.experience.contexts[n.id],y=n.y*scale;return `<a href="#maps/game-loop/${n.id}" aria-label="${E(c.title)} 화면과 내용 열기"><rect x="${n.x}" y="${y}" width="${n.w}" height="${n.h*scale}" rx="10" fill="${n.id===focus?'#e8d5ae':'#fffdf8'}" stroke="#aa956c" stroke-width="2"/><text x="${n.x+12}" y="${y+23}" font-size="18" fill="#172c30" font-weight="700">${E(n.label)}</text>${atlasPreview(c.preview,n.x+8,y+32,n.w-16,88)}<text x="${n.x+12}" y="${y+135}" font-size="11" fill="#64716c">${E(({starter:'실제 Godot 촬영',plan:'상태창 편집 참고안'})[n.id]||c.preview_kind)} · 눌러서 보기</text></a>`;}).join('')}</svg></div>
 <nav class="atlas-text-links" aria-label="화면 목록">${g.nodes.map(n=>`<a href="#maps/game-loop/${n.id}">${E(n.label)}</a>`).join('')}</nav>${focus?stagePanel(focus):'<p>상자 또는 화면 목록을 선택하세요. 키보드 Tab과 Enter로도 열 수 있습니다.</p>'}`;
};
home=function(){return originalHome()+`<nav class="overview-jumps" aria-label="전체 보기 바로가기">${[...D.reader_groups.map(g=>[g.id,g.label]),['work','작업·일정'],['proof','검수'],['continue','이어가기'],['reviews','내 코멘트']].map(([id,name])=>`<a href="#home/${id}">${E(name)}</a>`).join('')}</nav>`+
 D.reader_groups.map(g=>`<section id="overview-${g.id}" class="overview-group"><h2 class="group-heading">${E(g.label)}</h2>${g.id==='screens'?maps('game-loop')+'<div id="overview-chapters"></div>':''}${g.pages.map(id=>explanation(id,'all')).join('')}
 ${g.id==='route'?`<section id="overview-giyun">${giyunCatalog()}</section>`:''}
 ${g.id==='player'?`<section id="overview-manuals"><h2>보유 무공 · 성장 효과와 기술 연출</h2>${manualCatalog('all-manual')}</section>`:''}
 ${g.id==='characters'?`<h2>상대별 현재 데이터 · 성장과 전술</h2>${D.people.map(p=>people(p.id)).join('')}`:''}
 ${g.id==='combat'?`<section id="overview-library"><h2>격돌·합·피격 영상</h2>${movies('all-base',['clash-win','clash-lose','hit','block','evade','ultimate'])}</section>`:''}
 ${g.id==='audit'?auditGallery(true):''}</section>`).join('')+
 `<section id="overview-work">${pm(null,true)}</section><section id="overview-proof">${originalEvidence()}</section><section id="overview-continue">${resume()}</section>`;};
assets=function(){return `<p><a href="#motion">실제 격돌·합·카드 연출 영상 ${D.experience.clips.length}개 보기 →</a></p>`+originalAssets();};
evidence=function(){return `<p><a href="#motion">실제 Godot 연출 영상과 촬영 근거 보기 →</a></p>`+originalEvidence();};
const originalBind=bind;
bind=function(){originalBind();document.querySelectorAll('[data-video]').forEach(button=>button.onclick=()=>{const video=document.getElementById(button.dataset.video);if(video.paused){video.play().catch(()=>{document.getElementById('notice').textContent='영상 재생 실패 · MP4 열기로 원본을 확인해 주세요.';});}else video.pause();});document.querySelectorAll('[data-video-speed]').forEach(select=>select.onchange=()=>{document.getElementById(select.dataset.videoSpeed).playbackRate=Number(select.value);});};
