/* Atlas boxes are the navigation. All mechanics remain owned by Godot/data. */
const originalMaps=maps, originalHome=home, originalAssets=assets, originalEvidence=evidence;
function movie(clip, prefix='clip'){
 const id=prefix+'-'+clip.id;
 return `<article class="movie card" data-clip="${E(clip.id)}"><h3>${E(clip.title)}</h3>
 <video id="${E(id)}" controls playsinline preload="none" ${clip.poster?`poster="${E(src(clip.poster))}"`:""} aria-label="${E(clip.title)} 연출 영상"><source src="${E(src(clip.path))}" type="video/mp4"><a href="${E(src(clip.path))}">영상 직접 열기</a></video>
 <p class="video-message" data-video-message="${E(id)}" role="status">재생을 누르면 영상을 불러옵니다.</p><div class="row"><button data-video="${E(id)}">재생 / 일시정지</button><label>배속 <select data-video-speed="${E(id)}"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label><button data-video-retry="${E(id)}">다시 불러오기</button><a href="${E(src(clip.path))}" target="_blank" rel="noopener">MP4 열기 ↗</a></div>
 <p><small>${E(clip.caption || "이전 Godot 연출 기록")} · ${E(Number(clip.duration_seconds).toFixed(1))}초 · ${E(clip.audio_label||'음성 미포함')}<br>관측 결과: ${E(clip.outcomes.join(' / '))} · 기준 ${E(clip.source_revision.slice(0,10))}</small></p>${clip.visual_status==='STATIC_OR_EFFECT_ONLY'?'<div class="notice">이 상황은 현재 main에서 정적 결과 표시 위주입니다. 고유 캐릭터 움직임이 구현됐다고 표시하지 않습니다.</div>':''}
 <details><summary>촬영 상황과 원본 연결</summary><p>${clip.historical?'고정 상황의 연출 확인용입니다. 캠페인 플레이·재미·PR #342 검증과 구분합니다. 같은 동작을 공유하는 기술은 영상에서도 그대로 보입니다.':E(clip.limit)}</p>${clip.events.length?raw(clip.events,'Godot에 전달된 실제 이벤트'):''}${link(clip.manifest || 'docs/blueprint/evidence/motion/manifest.json','촬영 시점·파일·사용처 근거')}${link('src/combat/combat_board_preview.gd','Godot 연출 구현')}</details></article>`;
}
function movies(prefix='movies', ids=null){
 const clips=D.experience.clips.filter(c=>!ids||ids.includes(c.id)),current=clips.filter(c=>!c.historical),historical=clips.filter(c=>c.historical);
 let html=current.length?`<section class="current-frame-movie"><h2>현재 규칙의 실제 진행 영상</h2><p>출사표에서 첫 비무와 결과·복기까지 실제 게임에서 촬영했습니다. 첫 전투 10초는 정상 속도로 확인할 수 있습니다. 영상 파일과 확인서 검증은 사람의 재미·접근성·기기 검수를 대신하지 않습니다.</p><div class="movies selected-movie">${current.map(c=>movie(c,prefix)).join('')}</div></section>`:(!ids||ids.length===0?'<p class="notice">현재 10초 규칙의 전체 진행 영상은 촬영 확인서 검증 대기입니다.</p>':'');
 if(historical.length){const media=historical.length===1?`<div class="movies selected-movie">${movie(historical[0],prefix)}</div>`:`<div class="motion-gallery">${historical.map(c=>`<article class="card motion-card"><a href="#motion/${E(c.id)}">${c.poster?`<img loading="lazy" width="800" height="500" src="${E(src(c.poster))}" alt="${E(c.title)} 영상 첫 화면">`:`<div class="notice">▶ ${E(c.title)} · 영상 보기</div>`}<h3>${E(c.title)}</h3></a><p>${E(c.duration_seconds)}초 · ${E(c.outcomes.join(' / '))}</p><a class="play-link" href="#motion/${E(c.id)}">▶ 연출 보기</a></article>`).join('')}</div>`;
 const archive=`<div class="notice">아래 영상은 이전 슬롯 규칙의 촬영 기록입니다. 현재 10초 판정의 실행 증거와 구분하며, 당시 인물·먹 효과·실패 결과를 비교하는 역사 자료로 보존합니다.</div>${media}`;
 html+=ids?archive:`<details class="historical-movies"><summary>이전 규칙의 촬영 기록 · ${historical.length}개</summary>${archive}</details>`;}
 return html;
}
function cardSummary(card){return `<p>${E(({attack:'공격',response:'대응',recovery:'회복',move:'이동',movement:'이동',support:'보조',observation:'관찰',strengthen:'강화'})[card.category]??card.category)} · ${E(card.frame_timing_text??'현재 시간표 미연결')} · 기력 ${E(card.stamina_cost??0)} · 내력 ${E(card.internal_cost??0)} · 거리 ${E(card.range?card.range.min+'~'+card.range.max:(card.range_text??'—'))}</p>${card.effect_text?'<p>'+E(card.effect_text)+'</p>':''}${(card.effect_descriptions??[]).map(t=>'<p>'+E(t)+'</p>').join('')}${raw(card.effect_steps??card.effects??card,'효과와 발동 조건 · 원본 데이터')}`;}
function croppedImage(art,name){const [x,y,w,h]=art.region;return `<div class="sprite-window" style="--art-ratio:${w/h};aspect-ratio:${w}/${h}"><img loading="lazy" src="${E(src(art.path))}" alt="${E(name)}" style="width:${art.size[0]/w*100}%;left:${-x/w*100}%;top:${-y/h*100}%;" width="${art.size[0]}" height="${art.size[1]}"></div>`;}
function basicActionCards(start=0,count=10){const shared=D.image_catalog.find(r=>r.path===D.experience.actions[0].illustration.path);return `<section class="basic-actions"><h3>배치할 수 있는 기초 행동</h3><div class="basic-action-grid">${D.experience.actions.slice(start,start+count).map(a=>{const art=a.illustration,row=D.image_catalog.find(r=>r.path===art.path);return `<article class="card basic-action" data-basic-action="${E(a.id)}"><figure data-numbered-image="${E(art.path)}">${croppedImage(art,a.name+' · 게임에서 사용하는 삽화')}<figcaption>전투 · 이미지 ${row?.number??'—'} (${E(a.name)} 삽화)</figcaption></figure><h3>${E(a.name)}</h3>${cardSummary(a)}</article>`;}).join('')}</div><p>삽화는 게임에서 사용하는 같은 이미지 19의 영역입니다. 이름·비용·효과는 현재 게임 데이터에서 표시합니다.</p>${shared?userReviewPanel(recordById(shared.record_id)):''}</section>`;}
function manualCatalog(prefix='manual', focus=null){return commonGrowthTable()+`<div class="manuals">${D.manuals.filter(m=>!focus||m.manual_id===focus).map(m=>`<section class="panel" data-manual="${E(m.manual_id)}"><h2>${E(m.manual_name??m.name)}</h2>${manualTables(m)}${link('data/cards/martial_manuals/'+m.manual_id+'.json','무공 원본')}</section>`).join('')}</div>`;}
function groupedEventTable(headers,rows){return `<div class="table-wrap event-table"><table><thead><tr>${headers.map(h=>`<th scope="col">${E(h)}</th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>{const first=i===0||rows[i-1][0]!==row[0];let count=1;if(first)while(i+count<rows.length&&rows[i+count][0]===row[0])count++;return `<tr${first?' class="event-start"':''}>${first?`<th scope="rowgroup" rowspan="${count}">${E(row[0])}</th>`:''}${row.slice(1).map(v=>`<td>${E(v)}</td>`).join('')}</tr>`;}).join('')}</tbody></table></div>`;}
function screenGallery(blocks){const targets={rest:'#reader/reader-012',status:'#home/player',evade:'#reader/reader-023'};return `<div class="screen-gallery">${blocks.filter(b=>b.kind==='image').map(b=>`<article class="screen-card card" data-screen-context="${E(b.screen_context)}"><h3>${E(b.screen_label)}</h3>${block(b)}<a href="${E(targets[b.screen_context]||'#maps/game-loop/'+b.screen_context)}">관련 화면·설명 보기 →</a></article>`).join('')}</div>`+blocks.filter(b=>!['image','text'].includes(b.kind)).map(block).join('');}
function comparisonPicture(b){const row=imageByPath.get(b.path),revision=D.visual_revisions?.[b.path];if(revision?.page_ids?.includes(b.page_id))return {picture:block(b),review:''};return {picture:block({...b,defer_review:true}),review:row?userReviewPanel(recordById(row.record_id)):''};}
function comparisonRun(items,layout){
 if(layout==='image_runs'||layout==='portrait_gallery')return `<div class="screen-gallery ${layout==='portrait_gallery'?'portrait-gallery':''}">${items.map(x=>`<article class="screen-card card">${block(x.image)}${x.notes.map(block).join('')}</article>`).join('')}</div>`;
 if(layout==='sequence_table'){const media=comparisonPicture(items[0].image);return `<div class="sequence-comparison"><div class="comparison-picture">${media.picture}</div><div>${table(['순서','단계','발동 조건·처리'],items.map((x,i)=>[i+1,x.notes[0]?.text??'',x.notes.slice(1).filter(t=>t.text!=='→').map(t=>t.text).join('\n')]))}${media.review}</div></div>`;}
 if(layout==='tactics_table'){const columns=['별호','조합','약점','대응'];return `<div class="table-wrap"><table class="tactics-table"><thead><tr><th scope="col">상대·삽화</th>${columns.map(t=>`<th scope="col">${t}</th>`).join('')}<th scope="col">상태·코멘트</th></tr></thead><tbody>${items.map(x=>{const media=comparisonPicture(x.image);return `<tr><td><h3>${E(x.notes[0]?.text??'')}</h3>${media.picture}${x.notes.slice(1).filter(t=>!columns.some(k=>t.text.startsWith(k+'  '))).map(block).join('')}</td>${columns.map(k=>`<td>${x.notes.filter(t=>t.text.startsWith(k+'  ')).map(t=>E(t.text.slice(k.length).trim())).join('<br>')}</td>`).join('')}<td>${media.review}</td></tr>`;}).join('')}</tbody></table></div>`;}
 return `<div class="table-wrap"><table class="image-comparison-table"><thead><tr><th scope="col">이미지·번호·쓰임새</th><th scope="col">화면에 표시하는 정보</th><th scope="col">상태·코멘트</th></tr></thead><tbody>${items.map(x=>{const media=comparisonPicture(x.image);return `<tr><td>${media.picture}</td><td>${x.notes.map(block).join('')}</td><td>${media.review}</td></tr>`;}).join('')}</tbody></table></div>`;
}
function comparisonContent(p){let run=[],html='';const shared=p.shared_text_indices??[];const flush=()=>{if(run.length){html+=comparisonRun(run,p.layout);run=[];}};p.blocks.forEach((b,i)=>{if(shared.includes(i)){flush();if(i===shared[0])html+=`<div class="common-screen-info">${table(['공통 화면 정보','표시 내용'],shared.map(j=>[p.blocks[j].text==='대'?'양측 카드 비교':'현재 계획·즉시 결과',p.blocks[j].text]))}</div>`;}else if(b.kind==='image')run.push({image:b,notes:[]});else if(b.kind==='text'&&run.length)run[run.length-1].notes.push(b);else{flush();html+=block(b);}});flush();return html;}
function readerContent(p,prefix='reader'){if(p.layout==='screen_gallery')return screenGallery(p.blocks);if(['image_runs','image_table','sequence_table','portrait_gallery','tactics_table'].includes(p.layout))return comparisonContent(p);const manual=D.manuals.find(m=>p.title===(m.manual_name??m.name));if(manual)return manualTables(manual);return (p.id==='reader-065'?commonGrowthTable():'')+p.blocks.filter(b=>!(p.id==='reader-017'&&prefix==='stage'&&b.kind==='basic_actions')).map(block).join('');}
function explanation(id, prefix='explain'){const p=D.pages.find(p=>p.id===id);return p?`<article class="scroll-chapter" id="${E(prefix+'-'+id)}" data-reader="${E(id)}"><h2>${E(p.title)}</h2><p>${E(p.subtitle)}</p><p><small>${p.current_owner?'현재 승인 설명 · 실행·Human 검증 별도':'승인 당시 설명 · 현재 실행 검증과 구분'} · ${E(p.historical_state)}</small></p>${readerContent(p,prefix)}<details><summary>승인 당시 페이지와 배치 보기</summary><button class="media-button" data-image="${E(p.approved_page.url)}"><img loading="lazy" src="${E(p.approved_page.url)}" alt="승인 당시 ${E(p.title)} 페이지"></button></details><a href="#reader/${E(id)}">이 설명만 열기 →</a></article>`:'';}
function stagePanel(id){const c=D.experience.contexts[id];if(!c)return '';const node=D.diagrams[0].nodes.find(n=>n.id===id);const tasks=D.pm.items.filter(t=>(t.actual_consumers??[]).some(p=>node.sources.includes(p)));
 return `<section id="stage-detail" tabindex="-1" class="stage-detail"><div class="eyebrow">화면에서 이어서 확인</div><h2>${E(c.title)}</h2><a href="#maps/game-loop">← 전체 화면 구조로</a>
 ${c.manuals?manualCatalog('stage-manual'):''}
 ${c.constraints?`<h3>비무 제약 · 공개 정보</h3>${table(['이름','효과','선택 비용'],D.experience.constraints.constraints.map(x=>[x.display_name_ko,x.effect_summary_ko,x.selection_cost]))}${link('data/run/bimu_constraints.json','제약 원본')}<h3>상대별 정보와 무공</h3>${people(null,true)}`:''}
 ${c.actions?basicActionCards():''}
 ${c.clips?movies('stage',D.experience.clips.filter(c=>!c.historical).map(c=>c.id)):''}
 ${(c.additional_captures??[]).length?`<details class="additional-captures"><summary>이 단계의 추가 실행 화면</summary><div class="screen-gallery">${c.additional_captures.map(shot=>`<article class="screen-card card"><h3>${E(shot.label)}</h3>${block({kind:'image',path:shot.path,size:shot.size,page_id:'screen:'+id})}${link(shot.source,'촬영 확인서')}</article>`).join('')}</div></details>`:''}
 <div class="links">${node.sources.map(p=>link(p,"이 화면의 실제 구현" )).join('')}</div>${tasks.length?'<h3>연결된 작업</h3>'+tasks.map(t=>'<p><a href="#pm/'+E(t.work_item_id)+'">'+E(t.title??t.work_item_id)+'</a></p>').join(''):''}<h3>화면·규칙 설명과 아틀라스</h3>${c.pages.filter(p=>!(c.manuals&&p==='reader-065')).map(p=>explanation(p,'stage')).join('')}
 <nav class="stage-next" aria-label="다음 화면">${c.next.map(n=>`<a href="#maps/game-loop/${E(n)}">${E(D.experience.contexts[n].title)} · 다음 화면 →</a>`).join('')}</nav><p><a href="#pm">관련 구현·잔여 작업 확인</a> · <a href="#evidence">실행·검수 근거 확인</a></p></section>`;
}
function atlasPreview(preview,x,y,width,height){
 if(!preview)return `<rect x="${x}" y="${y}" width="${width}" height="${height}" fill="#eee6d8"/><text x="${x+width/2}" y="${y+height/2}" text-anchor="middle" fill="#64716c" font-size="14">실행 캡처 NOT_RUN</text>`;
 if(!preview.region)return `<image href="${E(src(preview.path))}" x="${x}" y="${y}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid meet"/>`;
 const [rx,ry,rw,rh]=preview.region;
 return `<svg x="${x}" y="${y}" width="${width}" height="${height}" viewBox="${preview.region.join(' ')}" overflow="hidden"><svg x="${rx}" y="${ry}" width="${rw}" height="${rh}" viewBox="${preview.region.join(' ')}" overflow="hidden"><image href="${E(src(preview.path))}" width="${preview.size[0]}" height="${preview.size[1]}"/></svg></svg>`;
}
maps=function(id,focus){const g=D.diagrams.find(d=>d.id===id)||D.diagrams[0];if(g.id!=='game-loop')return originalMaps(id,focus);
 const scale=1.6;
 return title('SCREEN ATLAS · CONNECTED FLOW','화면으로 보는 연결 구조','상자 안의 화면을 누르면 관련 무공·상대·행동·연출과 설명이 이어집니다.')+`<div class="row">${D.diagrams.map(d=>`<a class="badge" href="#maps/${d.id}">${E(d.title)}</a>`).join('')}</div><p>출사표부터 10초 비무·결과·복기까지 현재 승인 흐름입니다. 각 상자에 승인 배치 참고와 실제 실행 캡처를 구분해 표시합니다. 파일이 없는 화면은 NOT_RUN입니다.</p>
 <div class="diagram-viewport"><svg class="diagram atlas-diagram" viewBox="0 0 ${g.width} ${g.height*scale}" role="img" aria-label="화면 아틀라스 연결 구조"><defs><marker id="atlas-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#9a6b2b"/></marker></defs>
 ${g.edges.map(e=>`<g class="diagram-edge"><polyline points="${e.points.map(([x,y])=>x+','+y*scale).join(' ')}" fill="none" stroke="#9a6b2b" stroke-width="2" ${e.variant==='return'?'stroke-dasharray="6 4"':''} marker-end="url(#atlas-arrow)"/><text x="${e.label_at[0]}" y="${e.label_at[1]*scale}" text-anchor="middle" class="edge-label">${E(e.label)}</text></g>`).join('')}
 ${g.nodes.map(n=>{const c=D.experience.contexts[n.id],y=n.y*scale;return `<a href="#maps/game-loop/${n.id}" aria-label="${E(c.title)} 화면과 내용 열기"><rect x="${n.x}" y="${y}" width="${n.w}" height="${n.h*scale}" rx="10" fill="${n.id===focus?'#e8d5ae':'#fffdf8'}" stroke="#aa956c" stroke-width="2"/><text x="${n.x+12}" y="${y+23}" font-size="18" fill="#172c30" font-weight="700">${E(n.label)}</text>${atlasPreview(c.preview,n.x+8,y+32,n.w-16,88)}<text x="${n.x+12}" y="${y+135}" font-size="11" fill="#64716c">${E(c.preview_short??c.preview_kind)} · 열기</text></a>`;}).join('')}</svg></div>
 <nav class="atlas-text-links" aria-label="화면 목록">${g.nodes.map(n=>`<a href="#maps/game-loop/${n.id}">${E(n.label)}</a>`).join('')}</nav>${focus?stagePanel(focus):'<p>상자 또는 화면 목록을 선택하세요. 키보드 Tab과 Enter로도 열 수 있습니다.</p>'}`;
};
home=function(){return originalHome()+`<p><a href="../../docs/visual-assets/candidates/TEN-INK-STYLES-20260924/index.html#clash-preview">새 수묵 합 연출 크게 보기 →</a></p>`+`<nav class="overview-jumps" aria-label="전체 보기 바로가기">${[...D.reader_groups.map(g=>[g.id,g.label]),['work','작업·일정'],['proof','검수'],['continue','이어가기'],['reviews','내 코멘트']].map(([id,name])=>`<a href="#home/${id}">${E(name)}</a>`).join('')}</nav>`+
 D.reader_groups.map(g=>`<section id="overview-${g.id}" class="overview-group"><h2 class="group-heading">${E(g.label)}</h2>${g.id==='screens'?maps('game-loop')+'<div id="overview-chapters"></div>':''}${g.pages.map(id=>(id==='reader-065'?'<div id="overview-manuals"></div>':'')+explanation(id,'all')).join('')}
 ${g.id==='route'?`<section id="overview-giyun">${giyunCatalog()}</section>`:''}
 ${g.id==='characters'?`<h2>상대별 현재 데이터 · 성장과 전술</h2>${D.people.map(p=>people(p.id)).join('')}`:''}
 ${g.id==='combat'?`<section id="overview-library"><h2>실제 진행 영상과 이전 촬영 기록</h2>${movies('all-base')}</section>`:''}
 ${g.id==='audit'?auditGallery(true):''}</section>`).join('')+
 `<section id="overview-work">${pm(null,true)}</section><section id="overview-proof">${originalEvidence()}</section><section id="overview-continue">${resume()}</section>`;};
assets=function(){return `<p><a href="#motion">현재 진행 영상과 이전 촬영 기록 보기 →</a></p>`+originalAssets();};
evidence=function(){return `<p><a href="#motion">현재 Godot 진행 영상과 촬영 근거 보기 →</a></p>`+originalEvidence();};
const originalBind=bind;
function videoMessage(video,text){const output=document.querySelector(`[data-video-message="${video.id}"]`);if(output)output.textContent=text;}
function playVideo(video,reload=false){if(reload)video.load();videoMessage(video,'영상을 불러오는 중…');video.play().catch(error=>videoMessage(video,error.name==='NotAllowedError'?'재생 버튼을 다시 눌러 주세요.':'영상을 불러오지 못했습니다. 위의 연결 상태를 확인한 뒤 다시 불러오세요.'));}
bind=function(){originalBind();document.querySelectorAll('[data-video]').forEach(button=>button.onclick=()=>{const video=document.getElementById(button.dataset.video);if(video.paused)playVideo(video);else video.pause();});document.querySelectorAll('[data-video-retry]').forEach(button=>button.onclick=()=>playVideo(document.getElementById(button.dataset.videoRetry),true));document.querySelectorAll('[data-video-speed]').forEach(select=>select.onchange=()=>{document.getElementById(select.dataset.videoSpeed).playbackRate=Number(select.value);});document.querySelectorAll('video').forEach(video=>{video.addEventListener('playing',()=>videoMessage(video,'재생 중'));video.addEventListener('ended',()=>videoMessage(video,'재생 완료 · 다시 재생할 수 있습니다.'));video.addEventListener('error',()=>videoMessage(video,'영상 연결이 끊겼거나 파일을 읽을 수 없습니다. 연결 상태를 확인한 뒤 다시 불러오세요.'));video.querySelector('source')?.addEventListener('error',()=>videoMessage(video,'영상 파일을 불러오지 못했습니다. 「블루프린트 열기」로 연결을 확인해 주세요.'));});};
